// Fourteenth pass: current /reviews body-section variants (SSR HTML).
// These differ only in their closing clause from earlier variants —
// the new prefix-fallback in TranslationOverlay will also catch future
// ending edits, but we add the exact current strings for precise output.

export const AR_DICT_REVIEWS_V4: Record<string, string> = {
  "A prospect sees your ad, clicks the location, sees a thin or negative review profile, and chooses a competitor. You paid for the impression, the click and the bid premium, and the conversion went next door. Every marketing dirham past that point is subsidising a leaky funnel.":
    "العميل المحتمل يرى إعلانك، ينقر على العنوان، يجد ملف تقييمات ضعيفًا أو سلبيًا، فيختار منافسك. أنت دفعت ثمن الظهور، والنقرة، وعلاوة المزايدة — وذهب التحويل إلى الجوار. وكل درهم تُنفقه على التسويق بعد تلك النقطة إنما يدعم قمعًا مثقوبًا.",
  "ChatGPT, Google AI Overview, Perplexity and Gemini weight review depth, recency and sentiment heavily. A weak profile means the AI suggests a competitor by name, and you never appear in the answer at all. AI traffic is the channel that is growing fastest, and a poor review profile locks you out of it entirely.":
    "تعتمد ChatGPT و Google AI Overview و Perplexity و Gemini بشكل كبير على عمق التقييمات وحداثتها واتجاه المشاعر. الملف الضعيف يعني أن الذكاء الاصطناعي يُسمّي منافسك في الإجابة، وأنت لا تظهر فيها إطلاقًا. والزيارات القادمة من الذكاء الاصطناعي هي أسرع القنوات نموًا، وضعف ملف تقييماتك يُغلق هذا الباب أمامك تمامًا.",
  "Maps users skim ratings and review count before they read anything else. A low rating or fewer than 20 reviews drops your click-through rate to a fraction of what it should be, even when you outrank competitors on map position. You have the visibility, the customer just chooses someone else.":
    "مستخدمو الخرائط يُلقون نظرة سريعة على التقييم وعدد المراجعات قبل أي شيء آخر. التقييم المنخفض أو أقلّ من 20 تقييمًا يُسقط نسبة النقرات إلى جزء بسيط ممّا يجب أن تكون، حتى وإن كنت تتقدّم منافسيك في موقع الخريطة. الظهور لديك، لكن العميل ببساطة يختار سواك.",
  "Most businesses notice the symptoms first, fewer enquiries, lower marketing ROI, dropping organic traffic, long before they trace it back to reviews. By the time the pattern is obvious, six to twelve months of revenue has already gone to a better-reviewed competitor.":
    "تلاحظ معظم الشركات الأعراض أوّلًا — تراجع الاستفسارات، وضعف عائد التسويق، وانخفاض الزيارات العضوية — قبل وقت طويل من ربط ذلك بضعف ملف التقييمات. وبحلول الوقت الذي يتّضح فيه النمط، تكون من ستة إلى اثني عشر شهرًا من الإيرادات قد ذهبت إلى منافس بتقييم أفضل.",
  "On your own website we insert the JSON-LD schema markup (LocalBusiness, Service, FAQ, Review) that Google's Local Pack and AI Overview parsers rely on to rank and cite a business. Most competitor sites have none of this. Adding it correctly is one of the cheapest, highest-leverage ranking moves available.":
    "نُضيف على موقعك بيانات JSON-LD الوصفية (LocalBusiness و Service و FAQ و Review) التي تعتمد عليها محرّكات Local Pack في Google و AI Overview في ترتيب الأنشطة والاستشهاد بها. معظم مواقع المنافسين لا تتضمّن أيًّا من ذلك. وإضافتها بشكل صحيح من أرخص تحرّكات تحسين الترتيب وأعلاها أثرًا.",
  "Reputation damage happens in the hours between when something bad goes live and when anyone on your team notices. Our team is monitoring 24/7 so the work starts the moment the content appears, and continues every time it tries to reappear.":
    "ضرر السمعة يحدث في الساعات الفاصلة بين ظهور المحتوى السيئ وبين انتباه فريقك له. فريقنا يراقب على مدار الساعة طوال أيام الأسبوع، فيبدأ العمل لحظة ظهور المحتوى، ويتواصل في كل مرّة يحاول فيها الظهور من جديد.",
  "We audit your Google Business Profile, Apple Business Connect, Bing Places and the long tail of category-specific listings, roughly 200 sites in total, and align them so every NAP detail, category, opening hour, service area and image is correct, consistent and complete.":
    "نُجري تدقيقًا شاملًا لبياناتك على Google Business Profile و Apple Business Connect و Bing Places والمنصّات المتخصّصة بقطاعك، نحو 200 موقع إجمالًا، ونوحّدها لضمان أن يكون كل تفصيل — الاسم والعنوان والهاتف، والفئة، وساعات العمل، ومنطقة الخدمة، والصورة — دقيقًا ومتّسقًا ومكتملًا.",
  "We remove harmful reviews from Google, Trustpilot, Tripadvisor, Yelp and every major platform. The ones that cannot be taken down outright are suppressed beneath a steady flow of authentic positive reviews so they stop influencing buyers.":
    "نُزيل التقييمات المسيئة من Google و Trustpilot و Tripadvisor و Yelp وكافة المنصّات الكبرى. أمّا التي لا يمكن إزالتها مباشرةً، فنُغرقها تحت تدفّق منتظم من التقييمات الإيجابية الحقيقية، حتى تتوقّف عن التأثير في قرارات المشترين.",
  "We run authentic review growth campaigns across nearly 200 platforms, dispute and remove harmful content, optimise every listing with the structured-data markup search engines and AI engines actually read, and back the work with a written 90-day score guarantee. Miss the milestone, we work for free until it is met.":
    "نُنفّذ حملات حقيقية لنمو التقييمات على ما يقارب 200 منصّة، ونعترض على المحتوى المسيء ونعمل على إزالته، ونُحسّن بيانات كل منصّة بالبيانات المنظَّمة التي تقرؤها محركات البحث والذكاء الاصطناعي فعليًا، وندعم العمل بضمان كتابي لتحسّن التقييم خلال 90 يومًا. وإن لم نحقّق الهدف، نعمل مجانًا حتى نصل إليه.",
  "You see more authentic 5-star reviews on Google, Trustpilot, Tripadvisor and every platform that matters to your buyers, every single month. New volume, fresh dates, real customers. The kind of cadence that builds trust with prospects and the AI engines they ask.":
    "ستجد تقييمات حقيقية بخمس نجوم على Google و Trustpilot و Tripadvisor وكل منصّة يهتمّ بها عملاؤك، شهرًا بعد شهر. حجم جديد، وتواريخ حديثة، وعملاء حقيقيون. هذا هو الإيقاع الذي يبني الثقة لدى العملاء المحتملين ولدى محرّكات الذكاء الاصطناعي التي يسألونها.",
};
