// /insights batch F — 5 more articles (Fortune 500 playbook, executive privacy,
// lawyers negative reviews, employee privacy/ransomware, reputation monitoring vs action).
// Native Arabic. Brand names, %, AED/$/£ amounts, ratings, place names and dates kept in original form.
export const AR_DICT_INSIGHTS5: Record<string, string> = {
  "June 5, 2025":
    "5 يونيو 2025",
  "What Fortune 500 companies actually do that SMBs do not":
    "ما تفعله شركات Fortune 500 فعلًا ولا تفعله الشركات الصغيرة والمتوسّطة",
  "SMBs are now proportionally more exposed than enterprises":
    "الشركات الصغيرة والمتوسّطة باتت أكثر انكشافًا نسبيًا من الشركات الكبرى",
  "The price is now reachable":
    "السعر صار في المتناول الآن",
  "Our job is to run it":
    "مهمّتنا أن نشغّله",
  "For twenty years the largest companies on the planet have treated reputation defence as a permanent operational discipline. Coca-Cola, BP, HSBC, GSK, Saudi Aramco, Emirates Airline — each runs a continuous reputation operation that includes daily review monitoring, removal of harmful content where grounds permit, suppression of unfavourable search results with original company content, and a crisis-response retainer that can deploy within hours. The discipline is invisible to outsiders because it works.":
    "على مدى عشرين عامًا، عاملت أكبر شركات العالم الدفاع عن السمعة كتخصّص تشغيلي دائم. فـ Coca-Cola وBP وHSBC وGSK وSaudi Aramco وEmirates Airline — كلٌّ منها يشغّل عملية سمعة مستمرّة تشمل مراقبة يومية للتقييمات، وإزالة المحتوى الضارّ حيث تسمح الأسس، وإخماد نتائج البحث غير المواتية بمحتوى أصلي للشركة، وعقد استجابة للأزمات يمكن نشره خلال ساعات. وهذا التخصّص غير مرئي للخارج لأنه ينجح.",
  "Small and medium-sized businesses have historically assumed this kind of capability was out of reach. The Fortune 500 reputation playbook ran on Fortune 500 budgets, and the local dental practice, the family-run restaurant, the regional removals company simply did the best they could with the time they had. That assumption is now wrong. The same capability that defends a Fortune 500 brand can be deployed for an SMB — and our entire business is built on making it reachable.":
    "الشركات الصغيرة والمتوسّطة افترضت تاريخيًا أن هذا النوع من القدرة بعيد المنال. فدليل سمعة Fortune 500 كان يعمل بميزانيات Fortune 500، وعيادة الأسنان المحلّية، والمطعم العائلي، وشركة النقل الإقليمية كانوا ببساطة يبذلون أفضل ما يمكن بالوقت المتاح. ذلك الافتراض صار الآن خاطئًا. فالقدرة نفسها التي تدافع عن علامة Fortune 500 يمكن نشرها لشركة صغيرة ومتوسّطة، وعملنا بأكمله مبنيّ على جعلها في المتناول.",
  "The reputation playbook large enterprises run has four components. They monitor every review platform, every news mention and every social-media surface where the company name can appear. They remove content that breaches platform policy, that is defamatory, or that constitutes a regulated disclosure violation. They suppress unfavourable but legitimate content by pushing it below the visible search fold with original, authoritative company content. And they retain a crisis-response capability that can deploy within hours when a single incident threatens to define the brand for a year.":
    "دليل السمعة الذي تشغّله الشركات الكبرى له أربعة مكوّنات. يراقبون كل منصّة تقييم، وكل ذِكر إخباري، وكل سطح تواصل اجتماعي قد يظهر فيه اسم الشركة. ويزيلون المحتوى الذي يخالف سياسة المنصّة، أو يكون تشهيريًا، أو يشكّل مخالفة إفصاح منظَّمة. ويخمدون المحتوى غير المواتي لكن المشروع بدفعه أسفل الحدّ المرئي للبحث بمحتوى أصلي موثوق للشركة. ويحتفظون بقدرة استجابة للأزمات يمكن نشرها خلال ساعات حين تهدّد حادثة واحدة بتعريف العلامة لعام كامل.",
  "Each component is mature, repeatable and measured. The Fortune 500 reputation team does not see any of this as innovative — it is the operating baseline. The reason SMB owners read about reputation problems and assume there is no solution is that they have only been exposed to the surface — the public-facing news, the Google reviews — and have never had visibility into the defensive operation that runs underneath the brands they admire.":
    "كل مكوّن ناضج وقابل للتكرار ومقيس. فريق سمعة Fortune 500 لا يرى أيًّا من هذا مبتكرًا، بل هو خطّ الأساس التشغيلي. وسبب قراءة أصحاب الشركات الصغيرة والمتوسّطة عن مشكلات السمعة وافتراضهم عدم وجود حلّ هو أنهم لم يتعرّضوا إلا للسطح — الأخبار العامّة، وتقييمات Google — ولم تكن لديهم قط رؤية للعملية الدفاعية التي تعمل تحت العلامات التي يُعجَبون بها.",
  "Counter-intuitively, the small business is now more exposed to reputation damage than the large enterprise, not less. A single negative review on a dental practice with twelve reviews moves the average star rating visibly. A defamatory blog post about a regional removals company can outrank the company's own website inside a week. A disgruntled ex-employee on Glassdoor can drag a thirty-person company's rating from 4.6 to 2.9 inside a month. The same incident at Coca-Cola is invisible noise. At a fifty-employee SMB it is an existential event.":
    "على نحو معاكس للحدس، صارت الشركة الصغيرة الآن أكثر انكشافًا لضرر السمعة من الشركة الكبرى لا أقلّ. فتقييم سلبي واحد على عيادة أسنان لديها اثنا عشر تقييمًا يحرّك متوسّط تقييم النجوم بشكل مرئي. وتدوينة تشهيرية عن شركة نقل إقليمية قد تتفوّق على موقع الشركة نفسه خلال أسبوع. وموظّف سابق ساخط على Glassdoor قد يجرّ تقييم شركة من ثلاثين شخصًا من 4.6 إلى 2.9 خلال شهر. والحادثة نفسها في Coca-Cola ضجيج غير مرئي. أما في شركة صغيرة ومتوسّطة من خمسين موظّفًا فهي حدث وجودي.",
  "That asymmetry is the case for taking reputation defence seriously at SMB scale. The need is greater than the enterprise's because the revenue base is smaller and the margin for absorption is thinner. The intervention has to be continuous and professional rather than reactive and improvised.":
    "ذلك التفاوت هو المبرّر لأخذ الدفاع عن السمعة على محمل الجد على نطاق الشركات الصغيرة والمتوسّطة. فالحاجة أكبر منها لدى الشركة الكبرى لأن قاعدة الإيراد أصغر وهامش الاستيعاب أرقّ. والتدخّل يجب أن يكون مستمرًّا ومحترفًا لا تفاعليًا ومرتجلًا.",
  "What changed in the past five years is that the Fortune 500 playbook can now be delivered for SMBs at SMB pricing. The monitoring software exists at scale. The removal expertise has matured. The platform request mechanisms are documented. The positive-content pipeline can be operated efficiently. We can run, for a dental practice in Hampshire or a removals company in Sharjah, the exact same defensive operation that an in-house team runs for a £10bn corporate — at a monthly retainer that fits into the marketing budget.":
    "ما تغيّر في السنوات الخمس الماضية هو أن دليل Fortune 500 صار يمكن تقديمه للشركات الصغيرة والمتوسّطة بأسعار الشركات الصغيرة والمتوسّطة. فبرمجيات المراقبة موجودة على نطاق واسع. وخبرة الإزالة نضجت. وآليات طلبات المنصّات موثَّقة. وخطّ المحتوى الإيجابي يمكن تشغيله بكفاءة. ويمكننا أن نشغّل، لعيادة أسنان في Hampshire أو شركة نقل في الشارقة، العملية الدفاعية نفسها تمامًا التي يشغّلها فريق داخلي لشركة بقيمة £10bn — بعقد شهري يتّسع له ميزانية التسويق.",
  "That is the entire premise of our business. The Fortune 500 playbook is no longer a Fortune 500 budget. It is now a normal line item for any SMB that has decided its reputation is worth defending — and an unmissable one for any SMB whose reputation is the entire engine of new-customer acquisition.":
    "تلك هي فرضية عملنا بأكملها. فدليل Fortune 500 لم يعد ميزانية Fortune 500، بل صار بندًا عاديًا لأي شركة صغيرة ومتوسّطة قرّرت أن سمعتها تستحقّ الدفاع عنها، وبندًا لا يُفوَّت لأي شركة صغيرة ومتوسّطة تكون سمعتها المحرّك الكامل لاكتساب العملاء الجدد.",
  "We work with SMBs across the UK and the UAE — clinics, law firms, restaurants, hotels, removals companies, automotive dealerships, beauty salons, professional services — and we run the Fortune 500 reputation playbook on their behalf. Monitoring runs continuously. Harmful content comes down on the right grounds. Authoritative content is published to suppress what cannot be removed. A pipeline of recent positive feedback is maintained from real customers. A crisis-response capacity sits behind the operation for the day something goes badly wrong.":
    "نعمل مع الشركات الصغيرة والمتوسّطة في المملكة المتّحدة والإمارات — العيادات، ومكاتب المحاماة، والمطاعم، والفنادق، وشركات النقل، ومعارض السيارات، وصالونات التجميل، والخدمات المهنية — ونشغّل دليل سمعة Fortune 500 نيابةً عنهم. المراقبة تعمل باستمرار. والمحتوى الضارّ يُزال على الأسس الصحيحة. والمحتوى الموثوق يُنشَر لإخماد ما لا يمكن إزالته. وخطّ من التقييمات الإيجابية الحديثة يُصان من عملاء حقيقيين. وقدرة استجابة للأزمات تقبع خلف العملية لليوم الذي تسوء فيه الأمور بشدّة.",
  "The outcome the SMB client experiences is concrete. The Google profile that prospective customers see when they search the business reflects the business at its best, not the business at the mercy of its worst weekly review. The new-customer enquiry pipeline does not leak silently to competitors. The reputation does not have to be rebuilt every time something happens, because the defensive operation is already running. Same Fortune 500 playbook. Reachable at SMB price.":
    "النتيجة التي يختبرها العميل الصغير والمتوسّط ملموسة. فملف Google الذي يراه العملاء المحتملون حين يبحثون عن النشاط يعكس النشاط في أفضل حالاته، لا النشاط تحت رحمة أسوأ تقييم أسبوعي له. وخطّ استفسارات العملاء الجدد لا يتسرّب بصمت إلى المنافسين. والسمعة لا يلزم إعادة بنائها في كل مرّة يحدث فيها شيء، لأن العملية الدفاعية تعمل أصلًا. دليل Fortune 500 نفسه. في متناول سعر الشركات الصغيرة والمتوسّطة.",
  "Fortune 500 companies have run continuous reputation defence — monitoring, removal, suppression, positive content pipeline — for two decades. The discipline is mature, not experimental.":
    "شركات Fortune 500 شغّلت دفاعًا مستمرًّا عن السمعة — مراقبة، وإزالة، وإخماد، وخطّ محتوى إيجابي — على مدى عقدين. التخصّص ناضج لا تجريبي.",
  "The same capability that protects an FTSE 100 or Fortune 500 brand can be delivered for an SMB — the playbook is the same; the price is finally accessible.":
    "القدرة نفسها التي تحمي علامة FTSE 100 أو Fortune 500 يمكن تقديمها لشركة صغيرة ومتوسّطة، فالدليل هو نفسه، والسعر أخيرًا في المتناول.",
  "SMBs are now more exposed than enterprises to a single negative review or a defamatory blog post — the same one piece of content does proportionally more damage to a smaller revenue base.":
    "الشركات الصغيرة والمتوسّطة باتت أكثر انكشافًا من الشركات الكبرى لتقييم سلبي واحد أو تدوينة تشهيرية، فالقطعة الواحدة نفسها من المحتوى تُلحق ضررًا نسبيًا أكبر بقاعدة إيراد أصغر.",
  "Doing this work as a one-off project never delivers — reputation defence is a continuous discipline that decays the moment it stops.":
    "القيام بهذا العمل كمشروع لمرّة واحدة لا يأتي بنتيجة أبدًا، فالدفاع عن السمعة تخصّص مستمرّ يتلاشى لحظة توقّفه.",
  "Outcome we deliver: harmful content removed, recent positive profile maintained, top 3% Google Maps position held continuously — the same defensive posture that protects the largest brands in the world, now running for your business.":
    "النتيجة التي نقدّمها: المحتوى الضارّ يُزال، والملف الإيجابي الحديث يُصان، وموقع أعلى 3% على Google Maps يُحتفَظ به باستمرار — الوضع الدفاعي نفسه الذي يحمي أكبر العلامات في العالم، يعمل الآن لشركتك.",
  "The reputation playbook that has protected Fortune 500 companies for twenty years is now running for SMBs in the UK and the UAE. The capability is the same. The price is finally reachable. | Reputation Experts":
    "دليل السمعة الذي حمى شركات Fortune 500 طوال عشرين عامًا يعمل الآن للشركات الصغيرة والمتوسّطة في المملكة المتّحدة والإمارات. القدرة هي نفسها. والسعر أخيرًا في المتناول. | Reputation Experts",
  "June 15, 2025":
    "15 يونيو 2025",
  "What is actually exposed when you search the executive's name":
    "ما الذي ينكشف فعلًا حين تبحث عن اسم المسؤول التنفيذي",
  "What removing personal data from data brokers actually involves":
    "ما الذي تتضمّنه إزالة البيانات الشخصية من وسطاء البيانات فعلًا",
  "Suppression completes the privacy perimeter":
    "الإخماد يكمل محيط الخصوصية",
  "Executive privacy is our expertise":
    "خصوصية المسؤولين التنفيذيين هي تخصّصنا",
  "Most executives at the senior end of a UK or UAE company have never personally searched their own name on Google. When they do, the result is almost always alarming. Their home address is visible on three or four data-broker sites. Their spouse's name and employer is on LinkedIn one click away. Their children's school is in the local press from an unrelated event five years ago. Their personal mobile number is on a recruiter site from a job they did not take. A photograph of their car is on a property-listing site from when they sold a house. Every piece of that information is freely accessible by a hostile actor in ten minutes of search.":
    "معظم المسؤولين التنفيذيين في الطرف الأعلى من شركة بريطانية أو إماراتية لم يبحثوا قط شخصيًا عن أسمائهم على Google. وحين يفعلون، تكون النتيجة مقلقة دائمًا تقريبًا. فعنوان منزلهم مرئي على ثلاثة أو أربعة مواقع وسطاء بيانات. واسم زوجهم وجهة عمله على LinkedIn على بُعد نقرة واحدة. ومدرسة أطفالهم في الصحافة المحلّية من حدث غير ذي صلة قبل خمس سنوات. ورقم هاتفهم الجوّال الشخصي على موقع توظيف من وظيفة لم يقبلوها. وصورة لسيارتهم على موقع قوائم عقارية من حين باعوا منزلًا. وكل قطعة من تلك المعلومات متاحة بحرّية لفاعل معادٍ في عشر دقائق من البحث.",
  "This is no longer a hypothetical risk. Executive doxxing, targeted social engineering, ransomware attacks initiated through family-member phishing, and direct physical-security incidents at executive home addresses are now common enough that they are a board-level concern at every company we work with. The intervention is not advising the executive to update their LinkedIn privacy settings. The intervention is removing the data and suppressing the residual content in search — and we do it inside thirty days.":
    "لم يعد هذا خطرًا افتراضيًا. فالكشف المتعمّد عن بيانات المسؤولين التنفيذيين، والهندسة الاجتماعية المستهدفة، وهجمات الفدية التي تبدأ عبر تصيّد أفراد العائلة، وحوادث الأمن المادي المباشرة عند عناوين منازل المسؤولين التنفيذيين، باتت شائعة بما يكفي لتكون شاغلًا على مستوى مجلس الإدارة في كل شركة نعمل معها. والتدخّل ليس نصح المسؤول التنفيذي بتحديث إعدادات خصوصيته على LinkedIn، بل إزالة البيانات وإخماد المحتوى المتبقّي في البحث — ونفعل ذلك خلال ثلاثين يومًا.",
  "The first audit we run on a new executive client almost always returns the same pattern. The Google search of the executive's full name returns, on the first page: the corporate LinkedIn profile, two or three data-broker sites listing home address and approximate age, an unrelated press mention with family members named, the company press release that disclosed the executive's previous role, and a few social-media accounts the executive forgot they had. Page two and three add more data-broker sites, property records, and personal photographs from social-media tagged content the executive does not control.":
    "أول تدقيق نجريه على عميل تنفيذي جديد يعيد دائمًا تقريبًا النمط نفسه. فبحث Google عن الاسم الكامل للمسؤول التنفيذي يعيد، في الصفحة الأولى: ملف LinkedIn المؤسّسي، وموقعي أو ثلاثة مواقع وسطاء بيانات تدرج عنوان المنزل والعمر التقريبي، وذِكرًا صحفيًا غير ذي صلة بأسماء أفراد العائلة، وبيان الشركة الصحفي الذي أفصح عن منصب المسؤول التنفيذي السابق، وبضعة حسابات تواصل اجتماعي نسي المسؤول التنفيذي أنها لديه. والصفحتان الثانية والثالثة تضيفان مزيدًا من مواقع وسطاء البيانات، وسجلّات عقارية، وصورًا شخصية من محتوى موسوم على وسائل التواصل لا يتحكّم به المسؤول التنفيذي.",
  "Most of this content is technically public and was added by third parties without the executive's involvement. The executive did not consent to having their home address indexed by Spokeo or BeenVerified — those sites scraped public records and republished them. The executive did not tag themselves in the property listing — the estate agent did. The executive did not put the children's school in the local press — the school's PR team did, six years ago, for an entirely positive event. None of that absolves the executive of the risk it creates today.":
    "معظم هذا المحتوى عامّ تقنيًا وأضافه أطراف ثالثة دون مشاركة المسؤول التنفيذي. فهو لم يوافق على فهرسة عنوان منزله من Spokeo أو BeenVerified — تلك المواقع كشطت السجلّات العامّة وأعادت نشرها. ولم يضع وسمًا لنفسه في القائمة العقارية — الوكيل العقاري فعل. ولم يضع مدرسة الأطفال في الصحافة المحلّية — فريق العلاقات العامّة في المدرسة فعل، قبل ستّ سنوات، لحدث إيجابي تمامًا. ولا شيء من ذلك يعفي المسؤول التنفيذي من الخطر الذي يخلقه اليوم.",
  "Most data brokers have a removal mechanism. Spokeo, BeenVerified, PeopleFinder, Whitepages, Intelius, MyLife, Radaris and dozens of others each have their own removal form, their own verification process, and their own retention policy after the data has been removed. The total number of data-broker sites we work through on a typical UK or UAE executive engagement is between thirty and a hundred — each with a different process, each with a removal cycle of one to four weeks, and several with the unhelpful habit of re-listing the data months later from a new scrape.":
    "معظم وسطاء البيانات لديهم آلية إزالة. فـ Spokeo وBeenVerified وPeopleFinder وWhitepages وIntelius وMyLife وRadaris وعشرات غيرها، لكلٍّ منها نموذج إزالة خاص، وعملية تحقّق خاصة، وسياسة احتفاظ خاصة بعد إزالة البيانات. والعدد الإجمالي لمواقع وسطاء البيانات التي نعمل من خلالها في ارتباط تنفيذي بريطاني أو إماراتي نموذجي يتراوح بين ثلاثين ومئة — لكلٍّ منها عملية مختلفة، ودورة إزالة من أسبوع إلى أربعة، وعدّة منها لها العادة غير المفيدة بإعادة إدراج البيانات بعد أشهر من كشط جديد.",
  "Doing this at scale is a specialist process. It is not something an executive does in an evening, and it is not something the corporate IT team is set up to do. We run it as a continuous service — the initial removal sweep, the residual-suppression work for content that cannot be removed, and the ongoing re-listing monitoring that catches new appearances within days of them surfacing. The outcome is a search result that no longer exposes the executive's personal life.":
    "القيام بهذا على نطاق واسع عملية متخصّصة. ليس شيئًا يفعله المسؤول التنفيذي في أمسية، وليس شيئًا فريق تقنية المعلومات المؤسّسي مهيّأ للقيام به. نشغّله كخدمة مستمرّة — مسح الإزالة الأوّلي، وعمل إخماد المتبقّي للمحتوى الذي لا يمكن إزالته، ومراقبة إعادة الإدراج المستمرّة التي تلتقط الظهورات الجديدة خلال أيام من بروزها. والنتيجة نتيجة بحث لم تعد تكشف الحياة الشخصية للمسؤول التنفيذي.",
  "Some content cannot be removed. A legitimate news article from a reputable publication. A regulatory disclosure that has to remain accessible. A factual mention on a board member's company page. For all of these we do not chase removal — we build a body of professional content (interviews, conference appearances, opinion pieces, the executive's own blog) that ranks above the unwanted content in the search result. Within thirty days the executive's first page on Google is the version of their professional self they actually want the public to see.":
    "بعض المحتوى لا يمكن إزالته. مقال إخباري مشروع من منشور مرموق. أو إفصاح تنظيمي يجب أن يبقى متاحًا. أو ذِكر واقعي على صفحة شركة لعضو مجلس إدارة. ولكلّ هذه لا نلاحق الإزالة — بل نبني جسمًا من المحتوى المهني (مقابلات، وظهورات في مؤتمرات، ومقالات رأي، ومدوّنة المسؤول التنفيذي نفسه) يتصدّر المحتوى غير المرغوب في نتيجة البحث. وخلال ثلاثين يومًا تكون الصفحة الأولى للمسؤول التنفيذي على Google هي النسخة من ذاته المهنية التي يريد فعلًا أن يراها الجمهور.",
  "The combination — removal of the data-broker exposures plus suppression of the residual content — is what closes the digital perimeter around the executive. Personal address: gone. Family members' names: not findable from the executive's search. Children's school: not surfaced. Personal mobile: removed. Old photographs from third parties: pushed past the visible fold. The hostile actor doing reconnaissance on the executive now finds nothing useful.":
    "التركيبة — إزالة انكشافات وسطاء البيانات إضافةً إلى إخماد المحتوى المتبقّي — هي ما يغلق المحيط الرقمي حول المسؤول التنفيذي. العنوان الشخصي: زال. أسماء أفراد العائلة: غير قابلة للإيجاد من بحث المسؤول التنفيذي. مدرسة الأطفال: لم تعد تظهر. الجوّال الشخصي: أُزيل. الصور القديمة من أطراف ثالثة: دُفعت أسفل الحدّ المرئي. والفاعل المعادي الذي يجري استطلاعًا عن المسؤول التنفيذي لا يجد الآن شيئًا مفيدًا.",
  "We work with senior executives, family-office principals, regulated professionals and high-profile individuals across the UK and the UAE on personal reputation and digital privacy. The data-broker landscape is fragmented and constantly changing. The suppression playbook for personal search results is different from the playbook for a business. The protective outcome the client actually needs — being unfindable to a hostile actor — is achieved by combining the two.":
    "نعمل مع كبار المسؤولين التنفيذيين، وأصحاب المكاتب العائلية، والمهنيين الخاضعين للتنظيم، والشخصيات البارزة في المملكة المتّحدة والإمارات بشأن السمعة الشخصية والخصوصية الرقمية. مشهد وسطاء البيانات مجزّأ ويتغيّر باستمرار. ودليل إخماد نتائج البحث الشخصية مختلف عن دليل النشاط التجاري. والنتيجة الوقائية التي يحتاجها العميل فعلًا — أن يكون غير قابل للإيجاد من فاعل معادٍ — تتحقّق بدمج الاثنين.",
  "The outcome we deliver is concrete. The first three pages of Google search of the executive's name return nothing personally identifying. The data-broker sites that previously published the executive's address and family members no longer publish them. The residual content is monitored continuously and re-listings are removed within days. Same executive, same job, same public profile where it serves the business — and a personal perimeter that is finally closed.":
    "النتيجة التي نقدّمها ملموسة. الصفحات الثلاث الأولى من بحث Google عن اسم المسؤول التنفيذي لا تعيد أي شيء يعرّفه شخصيًا. ومواقع وسطاء البيانات التي كانت تنشر عنوان المسؤول التنفيذي وأفراد عائلته لم تعد تنشرها. والمحتوى المتبقّي يُراقَب باستمرار وإعادات الإدراج تُزال خلال أيام. المسؤول التنفيذي نفسه، والوظيفة نفسها، والملف العامّ نفسه حيث يخدم العمل — ومحيط شخصي مغلق أخيرًا.",
  "Senior executives' home addresses, family members and personal contact details are routinely indexed across dozens of data-broker sites and surface on the first page of Google.":
    "عناوين منازل كبار المسؤولين التنفيذيين، وأفراد عائلاتهم، وتفاصيل اتّصالهم الشخصية تُفهرَس روتينيًا عبر عشرات مواقع وسطاء البيانات وتظهر على الصفحة الأولى من Google.",
  "Executive doxxing and home-address targeting are now common enough to be a board-level security concern at most enterprises we work with.":
    "الكشف المتعمّد عن بيانات المسؤولين التنفيذيين واستهداف عناوين المنازل باتا شائعين بما يكفي ليكونا شاغلًا أمنيًا على مستوى مجلس الإدارة في معظم الشركات التي نعمل معها.",
  "Removing personal data from data brokers is a specialist process — most platforms have a removal mechanism, and most companies do not know how to use it at scale.":
    "إزالة البيانات الشخصية من وسطاء البيانات عملية متخصّصة، فمعظم المنصّات لها آلية إزالة، ومعظم الشركات لا تعرف كيف تستخدمها على نطاق واسع.",
  "Suppression in search is the complement to removal — content that cannot be removed can be pushed below the visible search fold within weeks.":
    "الإخماد في البحث مكمّل للإزالة، فالمحتوى الذي لا يمكن إزالته يمكن دفعه أسفل الحدّ المرئي للبحث خلال أسابيع.",
  "Outcome we deliver: nothing personally identifying about the executive is findable on the first three pages of a Google search of their name, inside thirty days.":
    "النتيجة التي نقدّمها: لا شيء يعرّف المسؤول التنفيذي شخصيًا يكون قابلًا للإيجاد على الصفحات الثلاث الأولى من بحث Google عن اسمه، خلال ثلاثين يومًا.",
  "Your home address, your spouse's name and your children's schools are on Google. We remove all of it inside thirty days. | Reputation Experts":
    "عنوان منزلك، واسم زوجك، ومدارس أطفالك على Google. نزيلها كلّها خلال ثلاثين يومًا. | Reputation Experts",
  "June 25, 2025":
    "25 يونيو 2025",
  "Who actually leaves bad lawyer reviews":
    "مَن يترك فعلًا تقييمات سيّئة للمحامين",
  "The public reply damages the firm more than the original review":
    "الردّ العلني يضرّ المكتب أكثر من التقييم الأصلي",
  "What we actually do for a firm with damaged reviews":
    "ما نفعله فعلًا لمكتب بتقييمات متضرّرة",
  "Law-firm reputation is our expertise":
    "سمعة مكاتب المحاماة هي تخصّصنا",
  "Negative reviews of law firms are unusual. The complaints often do not come from clients at all — they come from the other side of a matter, from a frustrated opposing party, from a disgruntled former employee, or from an entirely different person who has confused the firm with another practice of similar name. The complaint is loud, public, and frequently inaccurate. And the partner reading it is unusually likely to make the situation worse by replying.":
    "التقييمات السلبية لمكاتب المحاماة غير معتادة. فالشكاوى كثيرًا ما لا تأتي من العملاء أصلًا، بل من الطرف الآخر في قضية، أو من خصم محبَط، أو من موظّف سابق ساخط، أو من شخص مختلف تمامًا خلط بين المكتب وممارسة أخرى مشابهة الاسم. الشكوى صاخبة، وعلنية، وغير دقيقة كثيرًا. والشريك الذي يقرأها مرجَّح بشكل غير معتاد أن يزيد الموقف سوءًا بالردّ.",
  "Law firms in the UK and the UAE operate under regulatory regimes — the SRA in England and Wales, the DET in the UAE and equivalents across the Gulf — that constrain what a lawyer can say in public about any matter. The partner's public reply to a Google review therefore reads as either evasive or as a breach of professional conduct, and either way it is now a permanent part of the firm's search result. The right play is not a better reply. The right play is removal of the review, and rebuilding of the profile that prospective clients see when they look the firm up.":
    "مكاتب المحاماة في المملكة المتّحدة والإمارات تعمل تحت أنظمة تنظيمية — SRA في إنجلترا وويلز، وDET في الإمارات ومكافئاتها عبر الخليج — تقيّد ما يستطيع المحامي قوله علنًا عن أي قضية. لذا فإن ردّ الشريك العلني على تقييم Google يُقرأ إمّا كمراوغ أو كمخالفة للسلوك المهني، وفي الحالتين صار الآن جزءًا دائمًا من نتيجة بحث المكتب. والتحرّك الصحيح ليس ردًّا أفضل، بل إزالة التقييم، وإعادة بناء الملف الذي يراه العملاء المحتملون حين يبحثون عن المكتب.",
  "Most law-firm partners assume their negative Google reviews are from unhappy clients. In our experience working with practices across the UK and the UAE, that assumption is wrong more often than it is right. A significant share of negative reviews on law-firm profiles come from opposing parties in litigation, from third-party witnesses with no client relationship to the firm, from former employees, from members of the public who have confused the firm with another practice of similar name, or from competitors operating in bad faith.":
    "معظم شركاء مكاتب المحاماة يفترضون أن تقييماتهم السلبية على Google من عملاء غير راضين. ومن واقع خبرتنا في العمل مع ممارسات عبر المملكة المتّحدة والإمارات، يكون ذلك الافتراض خاطئًا أكثر مما يكون صحيحًا. فحصّة كبيرة من التقييمات السلبية على ملفات مكاتب المحاماة تأتي من خصوم في تقاضٍ، أو من شهود أطراف ثالثة بلا علاقة عميل بالمكتب، أو من موظّفين سابقين، أو من أفراد من العموم خلطوا بين المكتب وممارسة أخرى مشابهة الاسم، أو من منافسين يعملون بسوء نيّة.",
  "That matters because Google's review policy excludes most of these categories from valid reviews. A review from an opposing party in a matter is a conflict-of-interest review and removable. A review from someone with no actual service experience is removable. A defamatory factual claim is removable. The right grounds have to be cited on the right platform, and the firm has to know which review falls into which category — but most of the negative content on law-firm profiles can come down once that work is done.":
    "وهذا مهمّ لأن سياسة تقييمات Google تستبعد معظم هذه الفئات من التقييمات الصالحة. فتقييم من خصم في قضية هو تقييم تضارب مصالح وقابل للإزالة. وتقييم من شخص بلا تجربة خدمة فعلية قابل للإزالة. وادّعاء واقعي تشهيري قابل للإزالة. والأسس الصحيحة يجب الاستشهاد بها على المنصّة الصحيحة، وعلى المكتب أن يعرف أي تقييم يقع في أي فئة — لكن معظم المحتوى السلبي على ملفات مكاتب المحاماة يمكن أن يُزال بمجرّد إنجاز ذلك العمل.",
  "The partner reading a one-star review will reach for the keyboard. Within twenty-four hours the firm has a public reply on the Google profile — sometimes defending the work, sometimes asserting confidentiality, sometimes correcting the reviewer's account of events. Every variant has the same effect on the next prospective client who looks the firm up: the exchange is now the search result. The complaint is no longer one comment in a list. It is a public dispute with the firm as a visible participant.":
    "الشريك الذي يقرأ تقييمًا من نجمة واحدة سيمدّ يده إلى لوحة المفاتيح. وخلال أربع وعشرين ساعة يكون لدى المكتب ردّ علني على ملف Google — أحيانًا يدافع عن العمل، وأحيانًا يؤكّد السرّية، وأحيانًا يصحّح رواية المُقيِّم للأحداث. ولكل صيغة الأثر نفسه على العميل المحتمل التالي الذي يبحث عن المكتب: التبادل صار الآن نتيجة البحث. ولم تعد الشكوى تعليقًا واحدًا في قائمة، بل نزاعًا علنيًا والمكتب مشارك مرئي فيه.",
  "Worse, the reply almost always contains language a regulator will eventually flag. SRA and DET professional-conduct rules limit what a solicitor can say in public about any client matter. The partner's reply, drafted in twenty minutes of frustration, becomes a regulatory risk in its own right. The professional response to a bad review on a law-firm profile is no response — and removal of the review where the grounds permit it.":
    "والأسوأ أن الردّ يحتوي دائمًا تقريبًا على لغة سيرصدها منظِّم في النهاية. فقواعد السلوك المهني لـ SRA وDET تحدّ ما يستطيع المحامي قوله علنًا عن أي قضية عميل. وردّ الشريك، المصاغ في عشرين دقيقة من الإحباط، يصبح خطرًا تنظيميًا بحدّ ذاته. والاستجابة المهنية لتقييم سيّئ على ملف مكتب محاماة هي عدم الردّ — وإزالة التقييم حيث تسمح الأسس بذلك.",
  "We do not dispute reviews in public on the firm's behalf. We do not draft public replies. We remove. We assess every visible negative review for the specific Google or platform-policy ground that applies — conflict of interest, defamatory content, off-topic content, mistaken-identity content, content from a non-client — and we take it down where the ground holds. Where a review is the genuine opinion of an actual client and removal is not available, we suppress it: a steady, authentic pipeline of recent positive feedback from real clients pushes the older content below the visible review fold within weeks.":
    "نحن لا نجادل التقييمات علنًا نيابةً عن المكتب. ولا نصوغ ردودًا علنية. بل نزيل. نقيّم كل تقييم سلبي مرئي بحثًا عن الأساس المحدّد من سياسة Google أو المنصّة المنطبق — تضارب مصالح، أو محتوى تشهيري، أو محتوى خارج الموضوع، أو محتوى هوية مغلوطة، أو محتوى من غير عميل — ونزيله حيث يصمد الأساس. وحيث يكون التقييم رأيًا حقيقيًا لعميل فعلي ولا تتاح الإزالة، نُخمده: خطّ ثابت أصيل من التقييمات الإيجابية الحديثة من عملاء حقيقيين يدفع المحتوى الأقدم أسفل حدّ التقييمات المرئي خلال أسابيع.",
  "We do it on a timeline that protects the practice. Within 48 hours the assessment is complete and the platform requests are submitted. Within 30 days the visible recent profile is materially different. Within 60 days the new-client enquiry pipeline that had been quietly leaking to the competitor firm has returned. The firm's legal work has not changed. The profile that prospective clients see when they search has.":
    "نفعل ذلك على جدول زمني يحمي الممارسة. فخلال 48 ساعة يكتمل التقييم وتُقدَّم طلبات المنصّات. وخلال 30 يومًا يكون الملف الحديث المرئي مختلفًا بشكل ملموس. وخلال 60 يومًا يكون خطّ استفسارات العملاء الجدد الذي كان يتسرّب بهدوء إلى المكتب المنافس قد عاد. العمل القانوني للمكتب لم يتغيّر. الملف الذي يراه العملاء المحتملون حين يبحثون هو الذي تغيّر.",
  "We work with solicitors and barristers' chambers, commercial law firms, family practices, immigration specialists and in-house legal counsel across the UK and the UAE. Legal reputation is its own discipline. The regulatory constraints on what partners can say in public are different. The platforms prospective clients use — Google Business Profile for the local-area search, Legal 500 and Chambers for the directory presence, Trustpilot for the consumer-facing firms, and increasingly AI search overlays — each behave differently. The recovery playbook is specialist, not generic.":
    "نعمل مع المحامين وغرف المحامين، ومكاتب المحاماة التجارية، وممارسات الأسرة، وأخصّائيي الهجرة، والمستشارين القانونيين الداخليين في المملكة المتّحدة والإمارات. السمعة القانونية تخصّص قائم بذاته. فالقيود التنظيمية على ما يستطيع الشركاء قوله علنًا مختلفة. والمنصّات التي يستخدمها العملاء المحتملون — ملف Google Business للبحث المحلّي، وLegal 500 وChambers للحضور في الأدلّة، وTrustpilot للمكاتب الموجَّهة للمستهلك، وبشكل متزايد طبقات بحث الذكاء الاصطناعي — يسلك كلٌّ منها سلوكًا مختلفًا. ودليل التعافي متخصّص لا عامّ.",
  "The outcome we deliver is concrete. Reviews from non-clients, opposing parties and bad-faith actors come down on the right grounds. A recent profile of authentic client feedback comes online. The firm ranks in the top 3% of its category on Google Maps for its practice areas. The next prospective client who looks the firm up makes the call instead of calling the firm across the road. Same partners. Same expertise. Same fee scale. A different reputation, and a new-client pipeline that looks different with it.":
    "النتيجة التي نقدّمها ملموسة. التقييمات من غير العملاء، والخصوم، والفاعلين بسوء نيّة تُزال على الأسس الصحيحة. وملف حديث من تقييمات عملاء أصيلة يأتي عبر الإنترنت. وتحتلّ الممارسة أعلى 3% من فئتها على Google Maps لمجالات ممارستها. والعميل المحتمل التالي الذي يبحث عن المكتب يُجري المكالمة بدل الاتّصال بالمكتب في الجهة المقابلة من الشارع. الشركاء أنفسهم. الخبرة نفسها. سلّم الأتعاب نفسه. سمعة مختلفة، وخطّ عملاء جدد يبدو مختلفًا معها.",
  "Negative reviews of law firms often come from the other side of a matter, not from actual clients. Many are removable on platform-policy grounds.":
    "التقييمات السلبية لمكاتب المحاماة كثيرًا ما تأتي من الطرف الآخر في قضية، لا من عملاء فعليين. وكثير منها قابل للإزالة على أسس سياسة المنصّة.",
  "Replying to a negative review in public almost always escalates the exposure — the reply becomes part of the permanent search result.":
    "الردّ على تقييم سلبي علنًا يصعّد الانكشاف دائمًا تقريبًا، فالردّ يصبح جزءًا من نتيجة البحث الدائمة.",
  "SRA, DET and equivalent professional-conduct rules constrain what a partner can say in public. The professional response is no response.":
    "قواعد السلوك المهني لـ SRA وDET ومكافئاتها تقيّد ما يستطيع الشريك قوله علنًا. والاستجابة المهنية هي عدم الردّ.",
  "Suppression works: a pipeline of recent, authentic client feedback pushes older negative content below the visible review fold within weeks.":
    "الإخماد ينجح: خطّ من تقييمات العملاء الحديثة الأصيلة يدفع المحتوى السلبي الأقدم أسفل حدّ التقييمات المرئي خلال أسابيع.",
  "Outcome we deliver: removable reviews come down, a recent positive profile comes online, and the firm ranks in the top 3% of its category for its practice areas on Google.":
    "النتيجة التي نقدّمها: التقييمات القابلة للإزالة تُزال، وملف إيجابي حديث يأتي عبر الإنترنت، وتحتلّ الممارسة أعلى 3% من فئتها لمجالات ممارستها على Google.",
  "Bad Google reviews of a law firm rarely come from clients. We remove them — quietly, professionally and on the grounds that actually work. | Reputation Experts":
    "التقييمات السيّئة لمكتب محاماة على Google نادرًا ما تأتي من العملاء. نزيلها — بهدوء، وباحترافية، وعلى الأسس التي تنجح فعلًا. | Reputation Experts",
  "May 16, 2025":
    "16 مايو 2025",
  "How a ransomware attack actually starts":
    "كيف يبدأ هجوم الفدية فعلًا",
  "What cybersecurity software cannot do":
    "ما لا تستطيع برمجيات الأمن السيبراني فعله",
  "What we actually do for a company concerned about social-engineering risk":
    "ما نفعله فعلًا لشركة قلقة من خطر الهندسة الاجتماعية",
  "Employee privacy and social-engineering defence is our expertise":
    "خصوصية الموظّفين والدفاع ضد الهندسة الاجتماعية هما تخصّصنا",
  "Most successful ransomware attacks against UK and UAE companies in the last three years did not start with a vulnerability in the firewall or an unpatched server. They started with a phishing email or a phone call to a single employee whose personal information made them an easy target. The attacker knew the employee's name, their job, their reporting line, the names of their children, the dog walker they used, the school the children attended, the colleague they had lunch with on Tuesdays, and the password they had used on a forum in 2014 that had been leaked in a breach. The attack succeeded not because the technology failed, but because the employee was easy to impersonate.":
    "معظم هجمات الفدية الناجحة على الشركات البريطانية والإماراتية في السنوات الثلاث الأخيرة لم تبدأ بثغرة في الجدار الناري أو خادم غير مُحدَّث، بل ببريد تصيّد أو مكالمة هاتفية لموظّف واحد جعلت معلوماته الشخصية منه هدفًا سهلًا. فالمهاجم عرف اسم الموظّف، ووظيفته، وتسلسله الإداري، وأسماء أطفاله، ومن يمشّي كلبه، والمدرسة التي يرتادها الأطفال، والزميل الذي يتغدّى معه أيام الثلاثاء، وكلمة المرور التي استخدمها على منتدى عام 2014 وتسرّبت في اختراق. ونجح الهجوم لا لأن التقنية فشلت، بل لأن الموظّف كان سهل الانتحال.",
  "All of that information was freely available online before the attack. The firewall did not protect against it. The endpoint-detection software did not see it. The mandatory cybersecurity training did not remove it. The information sat on LinkedIn, on data-broker sites, in old breach databases, in social-media tagged photographs and in personal-life articles the employee had no involvement in publishing. The defensive move that closes that exposure is not security software. It is data removal — and that is what we do.":
    "كل تلك المعلومات كانت متاحة بحرّية عبر الإنترنت قبل الهجوم. الجدار الناري لم يحمِ منها. وبرمجيات كشف نقاط النهاية لم ترها. والتدريب الإلزامي على الأمن السيبراني لم يزِلها. فالمعلومات كانت تقبع على LinkedIn، وعلى مواقع وسطاء البيانات، وفي قواعد بيانات اختراقات قديمة، وفي صور موسومة على وسائل التواصل، وفي مقالات عن الحياة الشخصية لم يكن للموظّف دور في نشرها. والتحرّك الدفاعي الذي يغلق ذلك الانكشاف ليس برمجيات أمن، بل إزالة بيانات — وذلك ما نفعله.",
  "Forensic reports from the past three years of UK and UAE ransomware incidents are remarkably consistent on the initial vector. The attacker spent days or weeks compiling a dossier on a single target employee — typically someone in finance, HR or IT with access credentials that mattered. The dossier came from LinkedIn (job, reporting line, recent activity), from data brokers (home address, family members), from breach databases (passwords reused across personal accounts), from social-media tagged content (children's names, schools, holiday plans), and from search results for the employee's name across years of unrelated press mentions.":
    "التقارير الجنائية من السنوات الثلاث الأخيرة من حوادث الفدية البريطانية والإماراتية متّسقة بشكل لافت بشأن المتّجه الأوّلي. فالمهاجم قضى أيامًا أو أسابيع يجمّع ملفًّا عن موظّف هدف واحد — عادةً شخص في المالية أو الموارد البشرية أو تقنية المعلومات يملك بيانات اعتماد وصول مهمّة. والملف جاء من LinkedIn (الوظيفة، والتسلسل الإداري، والنشاط الأخير)، ومن وسطاء البيانات (عنوان المنزل، وأفراد العائلة)، ومن قواعد بيانات الاختراقات (كلمات مرور أُعيد استخدامها عبر حسابات شخصية)، ومن المحتوى الموسوم على وسائل التواصل (أسماء الأطفال، والمدارس، وخطط العطلات)، ومن نتائج البحث عن اسم الموظّف عبر سنوات من الذِّكر الصحفي غير ذي الصلة.",
  "Armed with that dossier, the attacker placed a phone call or sent an email that the employee could not distinguish from a legitimate communication. The CEO appeared to call from the right number, used the employee's name correctly, referenced a recent business event accurately, and asked the employee to authorise a transfer or click a link. The employee complied. The breach began. The technical security stack the company had invested in was never tested, because it was never the vector.":
    "مسلّحًا بذلك الملف، أجرى المهاجم مكالمة هاتفية أو أرسل بريدًا لم يستطع الموظّف تمييزه عن تواصل مشروع. فالرئيس التنفيذي بدا أنه يتّصل من الرقم الصحيح، واستخدم اسم الموظّف بشكل صحيح، وأشار إلى حدث عمل أخير بدقّة، وطلب من الموظّف اعتماد تحويل أو النقر على رابط. فامتثل الموظّف. وبدأ الاختراق. ومنظومة الأمن التقني التي استثمرت فيها الشركة لم تُختَبَر قط، لأنها لم تكن قط المتّجه.",
  "Endpoint-detection-and-response platforms, firewalls, multi-factor authentication, security-awareness training and the rest of the modern cybersecurity stack all defend against attacks that have already crossed the perimeter or are attempting to. None of them removes the personal information about your employees that the attacker uses to plan and execute the social-engineering call in the first place. The CISO can buy every product on the market and the employee's home address, family names and prior passwords will still be sitting on the same data-broker sites, the same LinkedIn over-share, the same breach databases — fully available to the next attacker who decides the company is worth targeting.":
    "منصّات كشف نقاط النهاية والاستجابة لها، والجدر النارية، والمصادقة متعدّدة العوامل، والتدريب على الوعي الأمني، وبقية منظومة الأمن السيبراني الحديثة، كلّها تدافع ضد هجمات عبرت المحيط بالفعل أو تحاول. ولا شيء منها يزيل المعلومات الشخصية عن موظّفيك التي يستخدمها المهاجم لتخطيط وتنفيذ مكالمة الهندسة الاجتماعية من الأساس. فمدير أمن المعلومات يستطيع شراء كل منتج في السوق، وسيظل عنوان منزل الموظّف، وأسماء عائلته، وكلمات مروره السابقة، تقبع على مواقع وسطاء البيانات نفسها، والإفراط في المشاركة على LinkedIn نفسه، وقواعد بيانات الاختراقات نفسها — متاحة بالكامل للمهاجم التالي الذي يقرّر أن الشركة تستحقّ الاستهداف.",
  "Closing that exposure requires a different discipline. Data-broker removal at scale, LinkedIn perimeter audit, breach-database monitoring, social-media privacy hardening, and continuous re-listing monitoring. Most security teams are not set up to do it. Most companies do not realise it is available as a service. It is, and it is the most underrated layer of an enterprise defence-in-depth strategy.":
    "إغلاق ذلك الانكشاف يتطلّب تخصّصًا مختلفًا. إزالة من وسطاء البيانات على نطاق واسع، وتدقيق محيط LinkedIn، ومراقبة قواعد بيانات الاختراقات، وتقوية الخصوصية على وسائل التواصل، ومراقبة إعادة الإدراج المستمرّة. ومعظم فِرَق الأمن غير مهيّأة للقيام به. ومعظم الشركات لا تدرك أنه متاح كخدمة. وهو متاح، وهو أكثر طبقات استراتيجية الدفاع المتعمّق المؤسّسي بخسًا في التقدير.",
  "We start with an exposure audit on the company's senior staff and high-risk employees — typically the executive team, the finance and HR leads, the IT operations team, and anyone with access credentials that materially matter. The audit catalogues every piece of personally identifying information about each employee that is publicly available, scored by attacker usefulness. Within the first thirty days, we remove the data-broker exposures, audit and lock down the LinkedIn perimeter, identify breach exposures and trigger credential resets, and scrub the social-media tagged content where consent can be obtained.":
    "نبدأ بتدقيق انكشاف على كبار موظّفي الشركة والموظّفين عالي الخطورة — عادةً الفريق التنفيذي، وقادة المالية والموارد البشرية، وفريق عمليات تقنية المعلومات، وأي شخص يملك بيانات اعتماد وصول مهمّة جوهريًا. والتدقيق يفهرس كل قطعة معلومات تعرّف كل موظّف شخصيًا متاحة للعموم، مصنَّفة بحسب فائدتها للمهاجم. وخلال الثلاثين يومًا الأولى، نزيل انكشافات وسطاء البيانات، وندقّق محيط LinkedIn ونحكمه، ونحدّد انكشافات الاختراقات ونطلق إعادة تعيين بيانات الاعتماد، ونمسح المحتوى الموسوم على وسائل التواصل حيث يمكن الحصول على الموافقة.",
  "We do not replace the cybersecurity stack — we close the gap the cybersecurity stack cannot reach. From month one onward we monitor for re-listings and new exposures, and we maintain a continuous defensive perimeter that the attacker now has to crack before they can even draft the phishing email. The next social-engineering attempt fails not because the technology detected it, but because the attacker could no longer assemble the dossier that makes it convincing.":
    "نحن لا نستبدل منظومة الأمن السيبراني — بل نغلق الفجوة التي لا تستطيع منظومة الأمن السيبراني بلوغها. فمن الشهر الأول فصاعدًا نراقب إعادات الإدراج والانكشافات الجديدة، ونصون محيطًا دفاعيًا مستمرًّا يتعيّن على المهاجم الآن اختراقه قبل أن يتمكّن حتى من صياغة بريد التصيّد. ومحاولة الهندسة الاجتماعية التالية تفشل لا لأن التقنية رصدتها، بل لأن المهاجم لم يعد قادرًا على تجميع الملف الذي يجعلها مقنعة.",
  "We work with enterprises and mid-market companies across the UK and the UAE on employee privacy and the data-removal layer of cybersecurity defence. The discipline is mature, the playbook is documented, and most of our engagements pay for themselves the first time a phishing or vishing attempt against a covered employee fails because the attacker did not have the personal data they expected to have.":
    "نعمل مع الشركات الكبرى والشركات متوسّطة السوق في المملكة المتّحدة والإمارات بشأن خصوصية الموظّفين وطبقة إزالة البيانات من الدفاع السيبراني. التخصّص ناضج، والدليل موثَّق، ومعظم ارتباطاتنا تسدّد تكلفتها أول مرّة تفشل فيها محاولة تصيّد أو تصيّد صوتي ضد موظّف مشمول لأن المهاجم لم يكن لديه البيانات الشخصية التي توقّع امتلاكها.",
  "The outcome we deliver is concrete. The employee data the attacker needs is removed from the public web and continuously monitored. The social-engineering vector closes. The cybersecurity stack the company has already invested in becomes more effective because it is now defending a perimeter that the attacker has fewer ways to penetrate. Same firewall. Same MFA. Same training. A different exposure profile, and a ransomware risk that has dropped sharply because the attack stops happening before it starts.":
    "النتيجة التي نقدّمها ملموسة. بيانات الموظّف التي يحتاجها المهاجم تُزال من الويب العامّ وتُراقَب باستمرار. ومتّجه الهندسة الاجتماعية يُغلَق. ومنظومة الأمن السيبراني التي استثمرت فيها الشركة بالفعل تصبح أكثر فاعلية لأنها الآن تدافع عن محيط لدى المهاجم طرق أقلّ لاختراقه. الجدار الناري نفسه. المصادقة متعدّدة العوامل نفسها. التدريب نفسه. ملف انكشاف مختلف، وخطر فدية انخفض بحدّة لأن الهجوم يتوقّف قبل أن يبدأ.",
  "Most ransomware attacks now begin with social engineering of a single employee — not with a vulnerability in the firewall or the endpoint.":
    "معظم هجمات الفدية تبدأ الآن بهندسة اجتماعية لموظّف واحد، لا بثغرة في الجدار الناري أو نقطة النهاية.",
  "The information the attacker uses to impersonate an employee — name, role, family members, schools, prior addresses, leaked passwords — is freely available online before the attack.":
    "المعلومات التي يستخدمها المهاجم لانتحال موظّف — الاسم، والدور، وأفراد العائلة، والمدارس، والعناوين السابقة، وكلمات المرور المسرّبة — متاحة بحرّية عبر الإنترنت قبل الهجوم.",
  "Cybersecurity software defends the perimeter. Employee privacy removal closes the route the attacker uses to get past the perimeter in the first place.":
    "برمجيات الأمن السيبراني تدافع عن المحيط. وإزالة خصوصية الموظّفين تغلق الطريق الذي يستخدمه المهاجم لتجاوز المحيط من الأساس.",
  "Data-broker removal at scale is a specialist process — most security teams are not set up to do it, and most companies do not know it is available.":
    "إزالة بيانات وسطاء البيانات على نطاق واسع عملية متخصّصة، فمعظم فِرَق الأمن غير مهيّأة للقيام بها، ومعظم الشركات لا تعرف أنها متاحة.",
  "Outcome we deliver: the personal data the attacker needs to impersonate or compromise an employee is removed from the public web and monitored for re-listings — so the social-engineering attack fails because the attacker can no longer assemble the dossier.":
    "النتيجة التي نقدّمها: البيانات الشخصية التي يحتاجها المهاجم لانتحال موظّف أو اختراقه تُزال من الويب العامّ وتُراقَب لإعادات الإدراج — فيفشل هجوم الهندسة الاجتماعية لأن المهاجم لم يعد قادرًا على تجميع الملف.",
  "Ransomware does not start in the firewall. It starts in your employees' LinkedIn profiles, data-broker listings and leaked passwords. We remove the data the attacker needs. | Reputation Experts":
    "الفدية لا تبدأ في الجدار الناري، بل في ملفات موظّفيك على LinkedIn، وقوائم وسطاء البيانات، وكلمات المرور المسرّبة. نزيل البيانات التي يحتاجها المهاجم. | Reputation Experts",
  "May 26, 2025":
    "26 مايو 2025",
  "What reputation monitoring software actually does":
    "ما تفعله برمجيات مراقبة السمعة فعلًا",
  "The action gap is where reputation value actually decays":
    "فجوة الفعل هي حيث تتآكل قيمة السمعة فعلًا",
  "What we actually do for a business currently relying on monitoring software":
    "ما نفعله فعلًا لشركة تعتمد حاليًا على برمجيات المراقبة",
  "Reputation action is our expertise":
    "الفعل في مجال السمعة هو تخصّصنا",
  "The reputation-software market in the UK and the UAE has grown rapidly over the last five years. Brand24, Mention, Reputation.com, Birdeye, Yotpo and a dozen others all sell the same essential service: continuous monitoring of where your business is mentioned, with alerts when something negative surfaces. The dashboards are polished, the email digests arrive on time, and the executives who buy them feel reassured that the company is on top of its reputation.":
    "سوق برمجيات السمعة في المملكة المتّحدة والإمارات نما بسرعة على مدى السنوات الخمس الأخيرة. فـ Brand24 وMention وReputation.com وBirdeye وYotpo وعشرة غيرها جميعها تبيع الخدمة الجوهرية نفسها: مراقبة مستمرّة لأين يُذكَر نشاطك، مع تنبيهات حين يبرز شيء سلبي. اللوحات مصقولة، وملخّصات البريد تصل في موعدها، والمسؤولون التنفيذيون الذين يشترونها يشعرون بالطمأنينة بأن الشركة مسيطرة على سمعتها.",
  "It is a false sense of security. Knowing you have fourteen new negative reviews this month is not protection from those reviews. Knowing your Glassdoor rating dropped from 4.4 to 3.9 last quarter does not raise it back to 4.4. Knowing a defamatory blog post is now ranking on page one for your company's name does not remove the post. Monitoring is the comforting first half of the operation. Without the second half — the action that actually removes, suppresses and replaces the damaging content — the dashboard simply shows you a problem that quietly grows worse.":
    "إنه شعور زائف بالأمان. فمعرفة أن لديك أربعة عشر تقييمًا سلبيًا جديدًا هذا الشهر ليست حمايةً من تلك التقييمات. ومعرفة أن تقييمك على Glassdoor هبط من 4.4 إلى 3.9 الربع الماضي لا تعيده إلى 4.4. ومعرفة أن تدوينة تشهيرية صارت تتصدّر الصفحة الأولى لاسم شركتك لا تزيل التدوينة. المراقبة هي النصف الأول المريح من العملية. وبلا النصف الثاني — الفعل الذي يزيل ويُخمد ويستبدل المحتوى الضارّ فعلًا — تكتفي اللوحة بأن تُريك مشكلة تتفاقم بهدوء.",
  "Monitoring tools sit on top of the public web and the major review platforms and alert the buyer when new content mentioning the brand surfaces. Some are sophisticated — they cluster sentiment, identify the source, score the severity. Some are crude — they email a dashboard at 8am every Monday with a count of mentions. All of them share one structural limitation: they are observational. They tell you what has happened. They do not change what has happened, and they do not stop the next thing from happening.":
    "أدوات المراقبة تقبع فوق الويب العامّ ومنصّات التقييم الكبرى وتنبّه المشتري حين يبرز محتوى جديد يذكر العلامة. بعضها متطوّر — يجمّع المشاعر، ويحدّد المصدر، ويصنّف الخطورة. وبعضها بدائي — يرسل لوحةً بالبريد الساعة الثامنة صباح كل اثنين بعدد الذِّكر. وكلّها تشترك في قيد بنيوي واحد: إنها مراقِبة. تخبرك بما حدث. ولا تغيّر ما حدث، ولا توقف الشيء التالي من الحدوث.",
  "That limitation is invisible to a buyer on day one. The dashboard is impressive, the alerts feel proactive, and the brand reputation now has a visible workflow inside the company. It becomes painfully visible by month twelve, when the executive realises the negative reviews that were visible in January are still visible — only there are now eighteen more of them, and a new defamatory blog post has appeared on page one of Google that the monitoring tool flagged in March and that nobody has done anything about.":
    "ذلك القيد غير مرئي لمشترٍ في اليوم الأول. فاللوحة مبهرة، والتنبيهات تبدو استباقية، وسمعة العلامة صار لها الآن سير عمل مرئي داخل الشركة. ويصبح مرئيًا بشكل مؤلم بحلول الشهر الثاني عشر، حين يدرك المسؤول التنفيذي أن التقييمات السلبية التي كانت مرئية في يناير لا تزال مرئية — لكن صار هناك الآن ثمانية عشر تقييمًا إضافيًا منها، وظهرت تدوينة تشهيرية جديدة على الصفحة الأولى من Google رصدتها أداة المراقبة في مارس ولم يفعل أحد شيئًا حيالها.",
  "The damage to a business reputation does not happen at the moment a negative review is posted. It happens during the months and years that the negative review stays visible while no one is taking it down. Monitoring shows the executive the moment the review appears. Without an action capability, the review then sits there for months, getting indexed, getting cited by AI search overlays, getting read by prospective customers, and quietly draining new-business pipeline to the competitor across the road.":
    "الضرر بسمعة نشاط تجاري لا يحدث لحظة نشر تقييم سلبي، بل خلال الأشهر والسنوات التي يبقى فيها التقييم السلبي مرئيًا بينما لا أحد يزيله. المراقبة تُري المسؤول التنفيذي لحظة ظهور التقييم. وبلا قدرة على الفعل، يقبع التقييم بعدها هناك لأشهر، يُفهرَس، ويُستشهَد به من طبقات بحث الذكاء الاصطناعي، ويُقرأ من العملاء المحتملين، ويستنزف بهدوء خطّ الأعمال الجديدة إلى المنافس في الجهة المقابلة من الشارع.",
  "The gap between knowing about a piece of damaging content and removing it is where the actual reputation value is lost. Monitoring does not close that gap. A specialist removal operation closes it. Without the removal operation, monitoring is simply a more sophisticated way of watching the business be damaged.":
    "الفجوة بين معرفة قطعة محتوى ضارّة وإزالتها هي حيث تُفقَد قيمة السمعة الفعلية. المراقبة لا تغلق تلك الفجوة. عملية إزالة متخصّصة تغلقها. وبلا عملية الإزالة، المراقبة مجرّد طريقة أكثر تطوّرًا لمشاهدة النشاط يُضرَّر.",
  "Most of our new clients arrive with a monitoring tool already in place. The first month of our engagement uses that tool's historical data as the action plan. Every flagged negative review, every defamatory blog post, every problematic search result that the monitoring tool surfaced over the last twelve months becomes a removal target or a suppression target. By month two, the visible Google profile is materially cleaner than it has been in years — and the monitoring tool dashboard finally turns green, because the content the tool was flagging has actually been removed.":
    "معظم عملائنا الجدد يصلون وأداة مراقبة قائمة لديهم بالفعل. والشهر الأول من ارتباطنا يستخدم بيانات تلك الأداة التاريخية كخطّة عمل. فكل تقييم سلبي مرصود، وكل تدوينة تشهيرية، وكل نتيجة بحث مُشكلة أبرزتها أداة المراقبة خلال الأشهر الاثني عشر الأخيرة، تصبح هدف إزالة أو هدف إخماد. وبحلول الشهر الثاني، يكون ملف Google المرئي أنظف بشكل ملموس مما كان عليه منذ سنوات — وتتحوّل لوحة أداة المراقبة أخيرًا إلى الأخضر، لأن المحتوى الذي كانت الأداة ترصده أُزيل فعلًا.",
  "We are not opposed to monitoring software — most of our clients keep theirs in place alongside our work. But monitoring is the input to the operation, not the operation itself. Until someone acts on the alerts, the dashboard is a measure of the damage, not a defence against it.":
    "لسنا ضد برمجيات المراقبة — فمعظم عملائنا يبقون على أدواتهم قائمة إلى جانب عملنا. لكن المراقبة هي مُدخَل العملية، لا العملية نفسها. وإلى أن يتصرّف أحد بناءً على التنبيهات، تبقى اللوحة مقياسًا للضرر، لا دفاعًا ضدّه.",
  "We work with SMBs and mid-market enterprises across the UK and the UAE that are tired of being told their reputation is healthy because the monitoring dashboard is updated. Our job is not to alert. Our job is to act. Harmful content comes down on the grounds that work. Suppression content goes up where removal is not available. Recent positive feedback comes online from real customers. The crisis-response retainer is there for the day a single incident threatens to define the company for a year.":
    "نعمل مع الشركات الصغيرة والمتوسّطة والشركات متوسّطة السوق في المملكة المتّحدة والإمارات التي سئمت أن يُقال لها إن سمعتها سليمة لأن لوحة المراقبة مُحدَّثة. مهمّتنا ليست التنبيه، بل الفعل. المحتوى الضارّ يُزال على الأسس التي تنجح. ومحتوى الإخماد يُرفَع حيث لا تتاح الإزالة. والتقييمات الإيجابية الحديثة تأتي عبر الإنترنت من عملاء حقيقيين. وعقد الاستجابة للأزمات موجود لليوم الذي تهدّد فيه حادثة واحدة بتعريف الشركة لعام كامل.",
  "The outcome we deliver is concrete. The monitoring tool dashboard turns green because the damage the tool was reporting is no longer there. The Google profile that prospective customers see is what the business actually deserves. The reputation, measured the way customers experience it, is finally what executives have been paying monitoring software to tell them it should be. Same business. Same team. Same product. A different reputation, and a defensive operation that finally does something with the dashboard.":
    "النتيجة التي نقدّمها ملموسة. لوحة أداة المراقبة تتحوّل إلى الأخضر لأن الضرر الذي كانت الأداة تبلّغ عنه لم يعد موجودًا. وملف Google الذي يراه العملاء المحتملون هو ما يستحقّه النشاط فعلًا. والسمعة، مقيسةً بالطريقة التي يختبرها بها العملاء، صارت أخيرًا ما كان المسؤولون التنفيذيون يدفعون لبرمجيات المراقبة لتخبرهم أنه ينبغي أن تكون. النشاط نفسه. الفريق نفسه. المنتج نفسه. سمعة مختلفة، وعملية دفاعية تفعل أخيرًا شيئًا باللوحة.",
  "Reputation monitoring software shows you what is wrong. It does not fix what is wrong — and the gap between the two is where companies lose the most reputation value.":
    "برمجيات مراقبة السمعة تُريك ما هو خاطئ. ولا تُصلح ما هو خاطئ — والفجوة بين الاثنين هي حيث تخسر الشركات أكبر قدر من قيمة السمعة.",
  "Companies who buy monitoring tools without an action capability typically end up with a year of evidence that the problem grew while they watched.":
    "الشركات التي تشتري أدوات المراقبة بلا قدرة على الفعل تنتهي عادةً بعام من الأدلّة على أن المشكلة نمت بينما كانوا يشاهدون.",
  "The dashboard only ever turns green when someone removes the harmful content, suppresses what cannot be removed, and brings recent positive content online. That is not what software does. That is what specialists do.":
    "اللوحة لا تتحوّل إلى الأخضر إلا حين يزيل أحدٌ المحتوى الضارّ، ويُخمد ما لا يمكن إزالته، ويأتي بمحتوى إيجابي حديث عبر الإنترنت. وذلك ليس ما تفعله البرمجيات، بل ما يفعله المتخصّصون.",
  "Most SMBs we work with had been paying for monitoring software for years before they engaged us — and the monitoring data we inherited became the action plan we executed against in the first ninety days.":
    "معظم الشركات الصغيرة والمتوسّطة التي نعمل معها كانت تدفع لبرمجيات المراقبة لسنوات قبل أن تتعاقد معنا، وبيانات المراقبة التي ورثناها صارت خطّة العمل التي نفّذنا عليها في التسعين يومًا الأولى.",
  "Outcome we deliver: not visibility into the problem, but the removal of the problem. The dashboard turns green because the damage is gone.":
    "النتيجة التي نقدّمها: ليست رؤيةً للمشكلة، بل إزالةً للمشكلة. اللوحة تتحوّل إلى الأخضر لأن الضرر زال.",
  "Knowing you have fourteen new negative reviews this month is not protection. Removing them is. The dashboard is not the work. | Reputation Experts":
    "معرفة أن لديك أربعة عشر تقييمًا سلبيًا جديدًا هذا الشهر ليست حماية. إزالتها هي الحماية. اللوحة ليست العمل. | Reputation Experts",
};
