// Three industry verticals: /restaurants-cafes, /aesthetic-cosmetic-clinics,
// /real-estate-agencies. Same template as hotels-resorts. Native Arabic.
// Brand names + AED/£ amounts stay Latin. (Some pages still carry leftover
// "UK" + £ copy from the original UK template — translated faithfully as shown.)

export const AR_DICT_VERTICALS: Record<string, string> = {

  // ═══════════ /restaurants-cafes ═══════════
  "Dubai Restaurants & Cafés | Multilingual Reputation Management with 90-Day Money-Back Guarantee | Reputation Experts":
    "مطاعم ومقاهي دبي | إدارة سمعة متعدّدة اللغات مع ضمان استرداد الأموال خلال 90 يومًا | خبراء السمعة",
  "Reputation Management for Restaurants & Cafes": "إدارة السمعة الرقمية للمطاعم والمقاهي",
  "Dubai restaurant and café reputation management": "إدارة السمعة الرقمية لمطاعم ومقاهي دبي",
  "Dubai restaurant reputation insight": "نظرة على واقع سمعة المطاعم في دبي",
  "Dubai’s only multilingual reputation team built for restaurants and cafés.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات للمطاعم والمقاهي.",
  "The Dubai dining reality": "واقع قطاع المطاعم في دبي اليوم",
  "For many UK restaurants,": "بالنسبة لكثير من المطاعم،",
  "Dubai restaurants rated below": "مطاعم دبي ذات التقييم الأقلّ من",
  "35% fewer new diners": "تستقطب روّادًا جددًا أقلّ بنسبة 35%",
  "attract": "استقطاب",
  "from search than peers rated 4.7 and above.": "من البحث مقارنةً بنظيراتها ذات التقييم 4.7 فأعلى.",
  "poor reviews mean losing £50,000 to £200,000+ per year":
    "ضعف التقييمات يعني خسارة تتراوح من 50,000 إلى أكثر من 200,000 جنيه إسترليني سنويًا",
  "On a venue serving 150 covers per day at AED 220 average spend, that gap is worth roughly":
    "بالنسبة لمطعم يخدم 150 طاولة يوميًا بمتوسط إنفاق 220 درهمًا، تُساوي هذه الفجوة تقريبًا",
  "in lost walk-ins and reservations, before considering the discount fees paid to win those same diners back through delivery and promo platforms.":
    "من الزيارات المباشرة والحجوزات المفقودة، قبل احتساب رسوم الخصومات التي تُدفع لاستعادة هؤلاء الروّاد أنفسهم عبر منصّات التوصيل والعروض.",
  "Source: Reputation Experts internal analysis, 46 Dubai restaurants and cafés, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 46 مطعمًا ومقهى في دبي خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "In 2026, over 90% of Dubai diners check Google reviews before trying a new restaurant or café. Reputation directly drives revenue. A venue with a poor online reputation loses customers to competitors every single day, even when the food, the service and the location are identical. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع أكثر من 90% من روّاد المطاعم في دبي على تقييمات Google قبل تجربة مطعم أو مقهى جديد. السمعة محرّك مباشر للإيرادات. والمطعم ذو السمعة الرقمية الضعيفة يخسر عملاءه لصالح منافسيه يوميًا، حتى وإن كان الطعام والخدمة والموقع متطابقة. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's hospitality market, reputation directly drives revenue. With more new venues opening every month and diners comparing more options than ever, a restaurant sitting at 4.0 stars loses guests to the 4.6-star venue next door every single night, even when the food, the service and the location are identical. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of authentic multilingual 5-star reviews that push it up, and ensuring your venue appears prominently when diners search on Google, ask ChatGPT for restaurant recommendations in Dubai, or browse Google AI Overviews. The result is more visibility, more walk-ins, and more confirmed reservations. Dubai clients typically see a 30 to 50% increase in new diner enquiries within the first three months.":
    "في سوق الضيافة بدبي، السمعة محرّك مباشر للإيرادات. ومع افتتاح مطاعم جديدة كل شهر ومقارنة الروّاد لعدد أكبر من الخيارات أكثر من أي وقت مضى، فإن مطعمًا بتقييم 4.0 نجوم يخسر روّاده لصالح المطعم المجاور صاحب الـ 4.6 نجمة كل ليلة، حتى وإن كان الطعام والخدمة والموقع متطابقة. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم ترفعه، ونضمن ظهور مطعمك بشكل بارز حين يبحث الروّاد على Google، أو يسألون ChatGPT عن توصيات مطاعم دبي، أو يتصفّحون إجابات Google AI Overview. والنتيجة: مزيد من الظهور، ومزيد من الزيارات المباشرة، ومزيد من الحجوزات المؤكّدة. يحقّق عملاؤنا في دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات الروّاد الجدد خلال أوّل ثلاثة أشهر.",
  "We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your venue at the top of Google Maps and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع مطعمك في صدارة Google Maps والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "We monitor your Google Business Profile around the clock, alongside how your venue surfaces in Google AI Overviews and ChatGPT recommendations. The moment a harmful review appears, in any language, our team is alerted and we begin the removal process immediately. If a review cannot be taken down, we craft a professional response on your behalf in the right language, showing prospective diners that your restaurant takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business على مدار الساعة، إلى جانب كيفية ظهور مطعمك في إجابات Google AI Overview وتوصيات ChatGPT. ولحظة ظهور تقييم مسيء، بأي لغة، يصل التنبيه إلى فريقنا ونبدأ إجراءات الإزالة فورًا. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للروّاد المحتملين أن مطعمك يأخذ ملاحظات ضيوفه بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "Real-time alerts whenever your restaurant is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة يُذكر فيها مطعمك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best restaurant near me\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific restaurants. Reputation Experts strengthens your entire digital presence so your restaurant is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your restaurant is featured in trusted media and reputable publications, something we specialise in, it creates the kind of authority signals that naturally improve how your restaurant is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل مطعم قريب\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بمطاعم بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى يكون مطعمك في موقع أفضل بكثير ليثق به ذكاء Google ويوصي به. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين يظهر مطعمك في وسائل إعلام موثوقة ومنشورات مرجعية — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف يُفهَم مطعمك ويُوصى به من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my restaurant boost reservations and increase sales?":
    "كيف يُساعد خبراء السمعة مطعمي على زيادة الحجوزات والمبيعات؟",
  "How does Google's AI Overview affect my restaurant?": "كيف تؤثّر إجابات Google AI Overview على مطعمي؟",
  "How does Reputation Experts build a strong online reputation for my restaurant?":
    "كيف يبني خبراء السمعة حضورًا رقميًا قويًا لمطعمي؟",
  "How long does it take to see results for my restaurant?": "كم من الوقت أحتاج حتى أرى نتائج فعلية لمطعمي؟",
  "We also ensure your venue appears prominently when diners search on Google or ask ChatGPT for restaurant recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the markets that matter: GCC, UK, Russia, India, China and Europe. More walk-ins, more reservations, and more orders direct to your venue. Dubai clients typically see a 30 to 50% increase in new diner enquiries within the first three months.":
    "كما نضمن ظهور مطعمك بشكل بارز حين يبحث الروّاد على Google، أو يسألون ChatGPT عن توصيات مطاعم دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأسواق التي تهمّك — دول الخليج، والمملكة المتحدة، وروسيا، والهند، والصين، وأوروبا. مزيد من الزيارات المباشرة، ومزيد من الحجوزات، ومزيد من الطلبات المباشرة إلى مطعمك. يحقّق عملاؤنا في دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات الروّاد الجدد خلال أوّل ثلاثة أشهر.",
  "Most Dubai restaurants and cafés see measurable improvement within 30 to 60 days. Review removal cases typically resolve in 1 to 3 weeks, depending on the platform, and our review generation system starts delivering authentic 5-star reviews, in Arabic, English, Russian, Chinese and other diner languages, within the first fortnight. By month three, you'll typically see a clear rating increase on Google, plus a stronger first page when diners search \"best brunch in Dubai\" or \"best Italian Marina\". Full reputation transformation, including Google AI Overview positioning and ChatGPT authority building, is a 4 to 6 month process.":
    "تشهد معظم مطاعم ومقاهي دبي تحسّنًا قابلًا للقياس خلال 30 إلى 60 يومًا. تُغلق قضايا إزالة التقييمات عادةً خلال 1 إلى 3 أسابيع، حسب المنصة، فيما يبدأ نظامنا لتوليد التقييمات بإحضار تقييمات حقيقية بخمس نجوم — بالعربية والإنجليزية والروسية والصينية وغيرها من لغات الروّاد — خلال أوّل أسبوعين. وبحلول الشهر الثالث، تلاحظ ارتفاعًا واضحًا في تقييمك على Google، وصفحة أولى أقوى حين يبحث الروّاد عن \"أفضل برانش في دبي\" أو \"أفضل مطعم إيطالي في المارينا\". أمّا التحوّل الكامل في السمعة — بما يشمل الظهور في Google AI Overview وبناء المرجعية في ChatGPT — فيمتدّ من 4 إلى 6 أشهر.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications - all in one integrated service built specifically for UK restaurants and cafes. Every strategy is shaped around how diners actually search for and choose their restaurant online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا للمطاعم والمقاهي. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها الروّاد فعليًا عن مطعمهم ويختارونه على الإنترنت.",
  "We work across three phases. First, we clean up: removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen: building a steady flow of authentic 5-star reviews from your real diners in their own languages, using follow-up systems timed around reservations and delivery orders, and publishing authoritative content that positions your venue as a trusted Dubai destination. Third, we establish long-term authority: securing press coverage in international travel and food publications, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من روّادك الفعليين بلغاتهم، عبر أنظمة متابعة مدروسة التوقيت حول الحجوزات وطلبات التوصيل، وننشر محتوى مرجعيًا يُرسّخ مكانة مطعمك كوجهة موثوقة في دبي. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية في المنشورات السياحية ومنشورات الطعام العالمية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join restaurants and cafes across the UAE who trust us to protect and grow their online presence.":
    "انضمّ إلى المطاعم والمقاهي في كافة الإمارات التي تثق بنا لحماية حضورها الرقمي وتنميته.",
  "Let's build a reputation your restaurant deserves.": "لِنبنِ معًا السمعة التي يستحقّها مطعمك.",

  // ═══════════ /aesthetic-cosmetic-clinics ═══════════
  "Dubai Aesthetic & Cosmetic Clinics | Multilingual Reputation Management with 90-Day Money-Back Guarantee | Reputation Experts":
    "عيادات التجميل والجلدية في دبي | إدارة سمعة متعدّدة اللغات مع ضمان استرداد الأموال خلال 90 يومًا | خبراء السمعة",
  "Reputation Management for Aesthetics Clinics": "إدارة السمعة الرقمية لعيادات التجميل",
  "Dubai aesthetic and cosmetic clinic reputation management": "إدارة السمعة الرقمية لعيادات التجميل والجلدية في دبي",
  "Dubai aesthetic clinic reputation insight": "نظرة على واقع سمعة عيادات التجميل في دبي",
  "Dubai’s only multilingual reputation team built for aesthetic and cosmetic clinics.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات لعيادات التجميل والجلدية.",
  "The Dubai aesthetics reality": "واقع قطاع التجميل في دبي اليوم",
  "For many UK cosmetic clinics,": "بالنسبة لكثير من عيادات التجميل،",
  "Dubai aesthetic clinics rated below": "عيادات التجميل في دبي ذات التقييم الأقلّ من",
  "31% fewer new patient enquiries": "تتلقّى استفسارات مرضى جدد أقلّ بنسبة 31%",
  "capture": "استقطاب",
  "On a clinic averaging AED 2,800 per treatment and 18 new patients per month, that gap is worth roughly":
    "بالنسبة لعيادة بمتوسط 2,800 درهم للجلسة و18 مريضًا جديدًا شهريًا، تُساوي هذه الفجوة تقريبًا",
  "in lost lifetime patient value, before considering the paid acquisition costs spent on Meta and Google Ads to win those same patients back.":
    "من القيمة العمرية المفقودة للمرضى، قبل احتساب تكاليف الاستقطاب المدفوعة على Meta و Google Ads لاستعادة هؤلاء المرضى أنفسهم.",
  "Source: Reputation Experts internal analysis, 29 Dubai aesthetic and cosmetic clinics, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 29 عيادة تجميل وجلدية في دبي خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "In 2026, 89% of Dubai patients read online reviews before booking an aesthetic or cosmetic consultation. Reputation directly drives revenue. A clinic with a poor online reputation loses patients to the clinic next door every single day, even when the clinical outcomes and the practitioners are identical. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع 89% من المرضى في دبي على التقييمات قبل حجز استشارة تجميل أو جلدية. السمعة محرّك مباشر للإيرادات. والعيادة ذات السمعة الرقمية الضعيفة تخسر مرضاها لصالح العيادة المجاورة يوميًا، حتى وإن كانت النتائج الطبية والأطبّاء متطابقين. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's aesthetics market, reputation directly drives revenue. 87% of patients check online reviews before booking a consultation. A clinic sitting at 4.0 stars loses patients to the 4.6-star clinic next door every single day, even when the practitioners, the equipment and the outcomes are identical. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of authentic multilingual 5-star reviews that push it up, and ensuring your clinic appears prominently when patients search on Google, ask ChatGPT for aesthetic clinic recommendations in Dubai, or browse Google AI Overviews. The result is more clicks, more calls, and more booked consultations. Dubai clinics typically see a 30 to 50% increase in new patient enquiries within the first three months.":
    "في سوق التجميل بدبي، السمعة محرّك مباشر للإيرادات. 87% من المرضى يطّلعون على التقييمات قبل حجز الاستشارة. والعيادة بتقييم 4.0 نجوم تخسر مرضاها لصالح العيادة المجاورة صاحبة الـ 4.6 نجمة يوميًا، حتى وإن كان الأطبّاء والأجهزة والنتائج متطابقة. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم ترفعه، ونضمن ظهور عيادتك بشكل بارز حين يبحث المرضى على Google، أو يسألون ChatGPT عن توصيات عيادات التجميل في دبي، أو يتصفّحون إجابات Google AI Overview. والنتيجة: مزيد من النقرات، ومزيد من المكالمات، ومزيد من الاستشارات المحجوزة. تحقّق عيادات دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات المرضى الجدد خلال أوّل ثلاثة أشهر.",
  "We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your clinic at the top of Google and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع عيادتك في صدارة بحث Google والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "We monitor your Google Business Profile around the clock, alongside how your clinic surfaces in Google AI Overviews and ChatGPT recommendations. The moment a harmful review appears, in any language, our team is alerted and we begin the removal process immediately. If a review cannot be taken down, we craft a professional response on your behalf in the right language, showing prospective patients that your clinic takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business على مدار الساعة، إلى جانب كيفية ظهور عيادتك في إجابات Google AI Overview وتوصيات ChatGPT. ولحظة ظهور تقييم مسيء، بأي لغة، يصل التنبيه إلى فريقنا ونبدأ إجراءات الإزالة فورًا. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للمرضى المحتملين أن عيادتك تأخذ ملاحظات مرضاها بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "Real-time alerts whenever your clinic is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة تُذكر فيها عيادتك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best aesthetics clinic near me\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific clinics. Reputation Experts strengthens your entire digital presence so your clinic is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your aesthetics clinic is featured in trusted media and reputable publications, something we specialise in, it creates the kind of authority signals that naturally improve how your clinic is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل عيادة تجميل قريبة\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بعيادات بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى تكون عيادتك في موقع أفضل بكثير ليثق بها ذكاء Google ويوصي بها. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين تظهر عيادتك في وسائل إعلام موثوقة ومنشورات مرجعية — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف تُفهَم عيادتك ويُوصى بها من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my clinic boost consultations and increase revenue?":
    "كيف يُساعد خبراء السمعة عيادتي على زيادة الاستشارات والإيرادات؟",
  "How does Google's AI Overview affect my aesthetics clinic?": "كيف تؤثّر إجابات Google AI Overview على عيادة التجميل لديّ؟",
  "How does Reputation Experts build a strong online reputation for my clinic?":
    "كيف يبني خبراء السمعة حضورًا رقميًا قويًا لعيادتي؟",
  "How long does it take to see results for my aesthetics clinic?": "كم من الوقت أحتاج حتى أرى نتائج فعلية لعيادة التجميل لديّ؟",
  "We also ensure your clinic appears prominently when patients search on Google or ask ChatGPT for aesthetic clinic recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the markets that matter: GCC, UK, Russia, India, China and Europe. More booked consultations, more confirmed treatments, and more repeat patients. Dubai clinics typically see a 30 to 50% increase in new patient enquiries within the first three months.":
    "كما نضمن ظهور عيادتك بشكل بارز حين يبحث المرضى على Google، أو يسألون ChatGPT عن توصيات عيادات التجميل في دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأسواق التي تهمّك — دول الخليج، والمملكة المتحدة، وروسيا، والهند، والصين، وأوروبا. مزيد من الاستشارات المحجوزة، ومزيد من الجلسات المؤكّدة، ومزيد من المرضى المتكرّرين. تحقّق عيادات دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات المرضى الجدد خلال أوّل ثلاثة أشهر.",
  "Most Dubai aesthetic and cosmetic clinics see measurable improvement within 30 to 60 days. Review removal cases typically resolve in 1 to 3 weeks, depending on the platform, and our review generation system starts delivering authentic 5-star reviews, in Arabic, English, Russian, Chinese and other patient languages, within the first fortnight. By month three, you'll typically see a clear rating increase on Google, plus a stronger first page when patients search \"best aesthetic clinic in Dubai\" or \"best cosmetic doctor Marina\". Full reputation transformation, including Google AI Overview positioning and ChatGPT authority building, is a 4 to 6 month process.":
    "تشهد معظم عيادات التجميل والجلدية في دبي تحسّنًا قابلًا للقياس خلال 30 إلى 60 يومًا. تُغلق قضايا إزالة التقييمات عادةً خلال 1 إلى 3 أسابيع، حسب المنصة، فيما يبدأ نظامنا لتوليد التقييمات بإحضار تقييمات حقيقية بخمس نجوم — بالعربية والإنجليزية والروسية والصينية وغيرها من لغات المرضى — خلال أوّل أسبوعين. وبحلول الشهر الثالث، تلاحظ ارتفاعًا واضحًا في تقييمك على Google، وصفحة أولى أقوى حين يبحث المرضى عن \"أفضل عيادة تجميل في دبي\" أو \"أفضل طبيب تجميل في المارينا\". أمّا التحوّل الكامل في السمعة — بما يشمل الظهور في Google AI Overview وبناء المرجعية في ChatGPT — فيمتدّ من 4 إلى 6 أشهر.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications - all in one integrated service built specifically for UK cosmetic and aesthetics clinics. Every strategy is shaped around how patients actually search for and choose their aesthetics clinic online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا لعيادات التجميل والجلدية. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها المرضى فعليًا عن عيادة التجميل ويختارونها على الإنترنت.",
  "We work across three phases. First, we clean up: removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen: building a steady flow of authentic 5-star reviews from your real patients in their own languages, using follow-up systems timed around treatments and consultations, and publishing authoritative content that positions your clinic as a trusted Dubai destination. Third, we establish long-term authority: securing press coverage in international beauty, health and lifestyle publications, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من مرضاك الفعليين بلغاتهم، عبر أنظمة متابعة مدروسة التوقيت حول الجلسات والاستشارات، وننشر محتوى مرجعيًا يُرسّخ مكانة عيادتك كوجهة موثوقة في دبي. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية في منشورات الجمال والصحة ونمط الحياة العالمية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join aesthetics clinics across the UAE who trust us to protect and grow their online presence.":
    "انضمّ إلى عيادات التجميل في كافة الإمارات التي تثق بنا لحماية حضورها الرقمي وتنميته.",
  "Let's build a reputation your clinic deserves.": "لِنبنِ معًا السمعة التي تستحقّها عيادتك.",

  // ═══════════ /real-estate-agencies ═══════════
  "Dubai Real Estate Agencies | Multilingual Reputation Management with 90-Day Money-Back Guarantee | Reputation Experts":
    "مكاتب العقارات في دبي | إدارة سمعة متعدّدة اللغات مع ضمان استرداد الأموال خلال 90 يومًا | خبراء السمعة",
  "Reputation Management for Estate & Letting Agents": "إدارة السمعة الرقمية لمكاتب العقارات والتأجير",
  "Dubai real estate agency": "مكتب عقارات في دبي",
  "Dubai real estate reputation insight": "نظرة على واقع سمعة العقارات في دبي",
  "Dubai’s only multilingual reputation team built for real estate agencies.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات لمكاتب العقارات.",
  "The Dubai property reality": "واقع قطاع العقارات في دبي اليوم",
  "For many UK estate and letting businesses,": "بالنسبة لكثير من مكاتب العقارات والتأجير،",
  "Dubai property agencies rated below": "مكاتب العقارات في دبي ذات التقييم الأقلّ من",
  "38% fewer qualified buyer enquiries": "تتلقّى استفسارات مشترين مؤهّلين أقلّ بنسبة 38%",
  "generate": "توليد",
  "On an agency closing 4 transactions per month at AED 2.5 million average ticket and 2% commission, that gap is worth roughly":
    "بالنسبة لمكتب يُغلق 4 صفقات شهريًا بمتوسط 2.5 مليون درهم للصفقة وعمولة 2%، تُساوي هذه الفجوة تقريبًا",
  "AED 9.1 million per year in lost gross commission": "9.1 مليون درهم سنويًا من إجمالي العمولات المفقودة",
  ", before considering the marketing budget redirected to chase those same buyers through portal listings and paid ads.":
    "، قبل احتساب الميزانية التسويقية المُوجَّهة لملاحقة هؤلاء المشترين أنفسهم عبر إعلانات البوابات العقارية والإعلانات المدفوعة.",
  "poor reviews mean losing £5,000 to £50,000+ per year":
    "ضعف التقييمات يعني خسارة تتراوح من 5,000 إلى أكثر من 50,000 جنيه إسترليني سنويًا",
  "Source: Reputation Experts internal analysis, 22 Dubai real estate agencies, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 22 مكتب عقارات في دبي خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "In 2026, over 85% of Dubai buyers and tenants check Google reviews before choosing a real estate brokerage or agent. Reputation directly drives revenue. A brokerage with a poor online reputation loses clients to the agency next door every single day, even when the listings, the locations and the agents are equally strong. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع أكثر من 85% من المشترين والمستأجرين في دبي على تقييمات Google قبل اختيار مكتب عقارات أو وكيل. السمعة محرّك مباشر للإيرادات. والمكتب ذو السمعة الرقمية الضعيفة يخسر عملاءه لصالح المكتب المجاور يوميًا، حتى وإن كانت القوائم العقارية والمواقع والوكلاء بالقوّة نفسها. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's property market, reputation directly drives revenue. With investors comparing dozens of brokerages before they pick up the phone, an agency sitting at 4.0 stars loses leads to the 4.6-star brokerage next door every single day, even when the inventory, the locations and the agents are equally strong. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of authentic multilingual 5-star reviews that push it up, and ensuring your brokerage appears prominently when buyers search on Google, ask ChatGPT for property recommendations in Dubai, or browse Google AI Overviews. The result is more qualified enquiries, more confirmed viewings, and more closed transactions. Dubai brokerages typically see a 30 to 50% increase in new client enquiries within the first three months.":
    "في سوق العقارات بدبي، السمعة محرّك مباشر للإيرادات. ومع مقارنة المستثمرين لعشرات المكاتب قبل أن يرفعوا السمّاعة، فإن مكتبًا بتقييم 4.0 نجوم يخسر عملاءه المحتملين لصالح المكتب المجاور صاحب الـ 4.6 نجمة يوميًا، حتى وإن كانت المحفظة العقارية والمواقع والوكلاء بالقوّة نفسها. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم ترفعه، ونضمن ظهور مكتبك بشكل بارز حين يبحث المشترون على Google، أو يسألون ChatGPT عن توصيات عقارات دبي، أو يتصفّحون إجابات Google AI Overview. والنتيجة: مزيد من الاستفسارات المؤهّلة، ومزيد من المعاينات المؤكّدة، ومزيد من الصفقات المُغلقة. تحقّق مكاتب دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your brokerage at the top of Google and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع مكتبك في صدارة بحث Google والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "We monitor your Google Business Profile around the clock, alongside how your brokerage surfaces in Google AI Overviews and ChatGPT recommendations. The moment a harmful review appears, in any language, our team is alerted and we begin the removal process immediately. If a review cannot be taken down, we craft a professional response on your behalf in the right language, showing prospective buyers and investors that your agency takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business على مدار الساعة، إلى جانب كيفية ظهور مكتبك في إجابات Google AI Overview وتوصيات ChatGPT. ولحظة ظهور تقييم مسيء، بأي لغة، يصل التنبيه إلى فريقنا ونبدأ إجراءات الإزالة فورًا. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للمشترين والمستثمرين المحتملين أن مكتبك يأخذ ملاحظات عملائه بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "Real-time alerts whenever your agency is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة يُذكر فيها مكتبك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best real estate agency Dubai\" or \"top off-plan broker Downtown\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific brokerages. Reputation Experts strengthens your entire digital presence so your agency is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your brokerage is featured in trusted property, business and lifestyle publications, something we specialise in, it creates the kind of authority signals that naturally improve how your agency is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل مكتب عقارات في دبي\" أو \"أفضل وسيط مشاريع على الخارطة في وسط المدينة\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بمكاتب بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى يكون مكتبك في موقع أفضل بكثير ليثق به ذكاء Google ويوصي به. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين يظهر مكتبك في منشورات عقارية واقتصادية ومنشورات نمط حياة موثوقة — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف يُفهَم مكتبك ويُوصى به من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my brokerage boost enquiries and close more deals?":
    "كيف يُساعد خبراء السمعة مكتبي على زيادة الاستفسارات وإغلاق صفقات أكثر؟",
  "How does Google's AI Overview affect my real estate brokerage?": "كيف تؤثّر إجابات Google AI Overview على مكتب العقارات لديّ؟",
  "How does Reputation Experts build a strong online reputation for my agency?":
    "كيف يبني خبراء السمعة حضورًا رقميًا قويًا لمكتبي؟",
  "How long does it take to see results for my estate and letting business?":
    "كم من الوقت أحتاج حتى أرى نتائج فعلية لمكتب العقارات والتأجير لديّ؟",
  "We also ensure your agency appears prominently when buyers and investors search on Google or ask ChatGPT for property recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the markets that matter: GCC, UK, Russia, India, China and Europe. More qualified enquiries, more confirmed viewings, and more closed transactions. Dubai brokerages typically see a 30 to 50% increase in new client enquiries within the first three months.":
    "كما نضمن ظهور مكتبك بشكل بارز حين يبحث المشترون والمستثمرون على Google، أو يسألون ChatGPT عن توصيات عقارات دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأسواق التي تهمّك — دول الخليج، والمملكة المتحدة، وروسيا، والهند، والصين، وأوروبا. مزيد من الاستفسارات المؤهّلة، ومزيد من المعاينات المؤكّدة، ومزيد من الصفقات المُغلقة. تحقّق مكاتب دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "Most Dubai real estate brokerages see measurable improvement within 30 to 60 days. Review removal cases typically resolve in 1 to 3 weeks, depending on the platform, and our review generation system starts delivering authentic 5-star reviews, in Arabic, English, Russian, Chinese and other buyer languages, within the first fortnight. By month three, you'll typically see a clear rating increase on Google, plus a stronger first page when investors search \"best real estate agency in Dubai\" or \"best off-plan broker Marina\". Full reputation transformation, including Google AI Overview positioning and ChatGPT authority building, is a 4 to 6 month process.":
    "تشهد معظم مكاتب العقارات في دبي تحسّنًا قابلًا للقياس خلال 30 إلى 60 يومًا. تُغلق قضايا إزالة التقييمات عادةً خلال 1 إلى 3 أسابيع، حسب المنصة، فيما يبدأ نظامنا لتوليد التقييمات بإحضار تقييمات حقيقية بخمس نجوم — بالعربية والإنجليزية والروسية والصينية وغيرها من لغات المشترين — خلال أوّل أسبوعين. وبحلول الشهر الثالث، تلاحظ ارتفاعًا واضحًا في تقييمك على Google، وصفحة أولى أقوى حين يبحث المستثمرون عن \"أفضل مكتب عقارات في دبي\" أو \"أفضل وسيط مشاريع على الخارطة في المارينا\". أمّا التحوّل الكامل في السمعة — بما يشمل الظهور في Google AI Overview وبناء المرجعية في ChatGPT — فيمتدّ من 4 إلى 6 أشهر.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications - all in one integrated service built specifically for UK estate and letting businesses. Every strategy is shaped around how clients actually search for and choose their estate or letting agent online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا لمكاتب العقارات والتأجير. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها العملاء فعليًا عن وكيل العقارات أو التأجير ويختارونه على الإنترنت.",
  "We work across three phases. First, we clean up: removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen: building a steady flow of authentic 5-star reviews from your real clients in their own languages, using follow-up systems timed around viewings, handovers and key collection, and publishing authoritative content that positions your brokerage as a trusted Dubai market leader. Third, we establish long-term authority: securing press coverage in international property and business publications, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من عملائك الفعليين بلغاتهم، عبر أنظمة متابعة مدروسة التوقيت حول المعاينات وعمليات التسليم واستلام المفاتيح، وننشر محتوى مرجعيًا يُرسّخ مكانة مكتبك كرائد موثوق في سوق دبي. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية في المنشورات العقارية والاقتصادية العالمية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join estate and letting businesses across the UAE who trust us to protect and grow their online presence.":
    "انضمّ إلى مكاتب العقارات والتأجير في كافة الإمارات التي تثق بنا لحماية حضورها الرقمي وتنميته.",
  "Let's build a reputation your agency deserves.": "لِنبنِ معًا السمعة التي يستحقّها مكتبك.",
};
