// fitness-spa-wellness, personal-care-beauty-salons, home-services.
// Same template. Native Arabic. Brand names + AED/£ stay Latin.

export const AR_DICT_VERTICALS3: Record<string, string> = {

  // ═══════════ /fitness-spa-wellness ═══════════
  "Dubai Fitness, Spa & Wellness | Multilingual Reputation Management with 90-Day Money-Back Guarantee | Reputation Experts":
    "اللياقة والسبا والعافية في دبي | إدارة سمعة متعدّدة اللغات مع ضمان استرداد الأموال خلال 90 يومًا | خبراء السمعة",
  "Dubai fitness, spa and wellness reputation management": "إدارة السمعة الرقمية لقطاع اللياقة والسبا والعافية في دبي",
  "Dubai fitness, spa and wellness reputation insight": "نظرة على واقع سمعة قطاع اللياقة والسبا والعافية في دبي",
  "Dubai’s only multilingual reputation team built for fitness, spa and wellness.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات لقطاع اللياقة والسبا والعافية.",
  "The Dubai fitness and wellness reality": "واقع قطاع اللياقة والعافية في دبي اليوم",
  "For many Dubai fitness, spa and wellness businesses,": "بالنسبة لكثير من أنشطة اللياقة والسبا والعافية في دبي،",
  "Dubai gyms, studios and spas rated below": "صالات وستوديوهات وسبا دبي ذات التقييم الأقلّ من",
  "39% fewer new-member trials": "تتلقّى تجارب أعضاء جدد أقلّ بنسبة 39%",
  "On a studio averaging 18 new members per month at AED 1,200 average monthly membership and a 12-month average tenure, that gap is worth roughly":
    "بالنسبة لستوديو بمتوسط 18 عضوًا جديدًا شهريًا برسوم عضوية شهرية 1,200 درهم ومدّة اشتراك متوسطها 12 شهرًا، تُساوي هذه الفجوة تقريبًا",
  "AED 1.5 million per year in lost lifetime member value": "1.5 مليون درهم سنويًا من القيمة العمرية المفقودة للأعضاء",
  ", before considering the paid acquisition spend redirected to win those same members back through Meta and Google Ads.":
    "، قبل احتساب إنفاق الاستقطاب المدفوع المُوجَّه لاستعادة هؤلاء الأعضاء أنفسهم عبر Meta و Google Ads.",
  "poor reviews mean losing £2,000 to £20,000+ per year":
    "ضعف التقييمات يعني خسارة تتراوح من 2,000 إلى أكثر من 20,000 جنيه إسترليني سنويًا",
  "Source: Reputation Experts internal analysis, 26 Dubai fitness, spa and wellness operators, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 26 منشأة لياقة وسبا وعافية في دبي خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "From gyms and boutique studios to yoga, pilates, day spas and personal trainers. We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your business at the top of Google and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "من الصالات الرياضية والستوديوهات المتخصّصة إلى اليوغا والبيلاتس والسبا اليومي والمدرّبين الشخصيين. نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع نشاطك في صدارة بحث Google والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "In 2026, over 85% of Dubai residents and visitors check Google reviews before joining a gym, booking a spa, trying a boutique studio or hiring a personal trainer. Reputation directly drives revenue. A wellness business with a poor online reputation loses members to the studio next door every single day, even when the trainers, the equipment and the location are equally strong. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع أكثر من 85% من المقيمين والزوار في دبي على تقييمات Google قبل الاشتراك في صالة رياضية، أو حجز سبا، أو تجربة ستوديو متخصّص، أو الاستعانة بمدرّب شخصي. السمعة محرّك مباشر للإيرادات. ونشاط العافية ذو السمعة الرقمية الضعيفة يخسر أعضاءه لصالح الستوديو المجاور يوميًا، حتى وإن كان المدرّبون والأجهزة والموقع بالقوّة نفسها. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's fitness and wellness market, reputation directly drives revenue. 85% of members check Google reviews before booking a trial (unless existing clients). A studio sitting at lower star ratings loses members to a competitor at a higher score every single day, even when the trainers, the equipment and the location are equally strong. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of new 5-star reviews that push it up, and ensuring your business appears prominently when potential members search on Google, ask ChatGPT, or browse AI Overviews. The result is more clicks, more calls, and more member enquiries, clients typically see a 30–50% increase in new member enquiries within the first three months.":
    "في سوق اللياقة والعافية بدبي، السمعة محرّك مباشر للإيرادات. 85% من الأعضاء يطّلعون على تقييمات Google قبل حجز تجربة (ما لم يكونوا عملاء سابقين). والستوديو ذو التقييم الأقل يخسر أعضاءه لصالح منافس بتقييم أعلى يوميًا، حتى وإن كان المدرّبون والأجهزة والموقع بالقوّة نفسها. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الجديدة بخمس نجوم ترفعه، ونضمن ظهور نشاطك بشكل بارز حين يبحث الأعضاء المحتملون على Google، أو يسألون ChatGPT، أو يتصفّحون إجابات AI Overview. والنتيجة: مزيد من النقرات، ومزيد من المكالمات، ومزيد من استفسارات الأعضاء — يحقّق عملاؤنا عادةً ارتفاعًا من 30% إلى 50% في استفسارات الأعضاء الجدد خلال أوّل ثلاثة أشهر.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best gym near me\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific businesss. Reputation Experts strengthens your entire digital presence so your business is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your fitness and wellness business is featured in trusted media and reputable publications, something we specialise in, it creates the kind of authority signals that naturally improve how your business is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل صالة رياضية قريبة\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بأنشطة بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى يكون نشاطك في موقع أفضل بكثير ليثق به ذكاء Google ويوصي به. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين يظهر نشاطك في وسائل إعلام موثوقة ومنشورات مرجعية — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف يُفهَم نشاطك ويُوصى به من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my fitness or wellness business boost new-member trials and increase revenue?":
    "كيف يُساعد خبراء السمعة نشاطي في اللياقة أو العافية على زيادة تجارب الأعضاء الجدد ورفع الإيرادات؟",
  "How does Google's AI Overview affect my fitness, spa or wellness business?": "كيف تؤثّر إجابات Google AI Overview على نشاطي في اللياقة أو السبا أو العافية؟",
  "How long does it take to see results for my Dubai fitness, spa or wellness business?": "كم من الوقت أحتاج حتى أرى نتائج فعلية لنشاطي في اللياقة أو السبا أو العافية في دبي؟",
  "We also ensure your business appears prominently when residents and visitors search on Google or ask ChatGPT for fitness, spa and wellness recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the markets that matter: GCC, UK, Russia, India, China and Europe. More new-member trials, more spa bookings, and more repeat sessions. Dubai operators typically see a 30 to 50% increase in new-member enquiries within the first three months.":
    "كما نضمن ظهور نشاطك بشكل بارز حين يبحث المقيمون والزوار على Google، أو يسألون ChatGPT عن توصيات اللياقة والسبا والعافية في دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأسواق التي تهمّك — دول الخليج، والمملكة المتحدة، وروسيا، والهند، والصين، وأوروبا. مزيد من تجارب الأعضاء الجدد، ومزيد من حجوزات السبا، ومزيد من الجلسات المتكرّرة. تحقّق منشآت دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات الأعضاء الجدد خلال أوّل ثلاثة أشهر.",
  "Most businesss see measurable improvement within 30 to 60 days. Review removal cases typically resolve in 1–3 weeks, depending on the platform, and our review generation system starts delivering new 5-star reviews within the first fortnight. By month three, you'll typically see a noticeable rating increase and a stronger first page on Google. Full reputation transformation - including AI Overview positioning and authority building - is a 4–6 month process.":
    "تشهد معظم الأنشطة تحسّنًا قابلًا للقياس خلال 30 إلى 60 يومًا. تُغلق قضايا إزالة التقييمات عادةً خلال 1 إلى 3 أسابيع، حسب المنصة، فيما يبدأ نظامنا لتوليد التقييمات بإحضار تقييمات جديدة بخمس نجوم خلال أوّل أسبوعين. وبحلول الشهر الثالث، تلاحظ ارتفاعًا واضحًا في تقييمك وصفحة أولى أقوى على Google. أمّا التحوّل الكامل في السمعة — بما يشمل الظهور في AI Overview وبناء المرجعية — فيمتدّ من 4 إلى 6 أشهر.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications, all in one integrated service built specifically for Dubai gyms, boutique studios, day spas, wellness centres and personal trainers. Every strategy is shaped around how Dubai members actually search for and choose a fitness, spa or wellness business online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا للصالات الرياضية والستوديوهات المتخصّصة والسبا اليومي ومراكز العافية والمدرّبين الشخصيين في دبي. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها الأعضاء في دبي فعليًا عن نشاط لياقة أو سبا أو عافية ويختارونه على الإنترنت.",
  "Real-time alerts whenever your studio or business is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة يُذكر فيها ستوديوك أو نشاطك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "We monitor your Google Business Profile around the clock, alongside how your business surfaces in Google AI Overviews and ChatGPT recommendations. The moment a harmful review appears, in any language, our team is alerted and we begin the removal process immediately. If a review cannot be taken down, we craft a professional response on your behalf in the right language, showing prospective members that your studio takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business على مدار الساعة، إلى جانب كيفية ظهور نشاطك في إجابات Google AI Overview وتوصيات ChatGPT. ولحظة ظهور تقييم مسيء، بأي لغة، يصل التنبيه إلى فريقنا ونبدأ إجراءات الإزالة فورًا. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للأعضاء المحتملين أن ستوديوك يأخذ ملاحظاتهم بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "We work across three phases. First, we clean up, removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen, building a steady flow of genuine 5-star reviews from your existing members using follow-up systems timed around bookings, and publishing authoritative content that positions your business as a trusted name online. Third, we establish long-term authority, securing press coverage, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من أعضائك الحاليين عبر أنظمة متابعة مدروسة التوقيت حول الحجوزات، وننشر محتوى مرجعيًا يُرسّخ مكانة نشاطك كاسم موثوق على الإنترنت. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join Dubai gyms, studios, spas and wellness operators who trust us to protect and grow their online presence.":
    "انضمّ إلى الصالات الرياضية والستوديوهات والسبا ومنشآت العافية في دبي التي تثق بنا لحماية حضورها الرقمي وتنميته.",
  "Let's build a reputation your studio deserves.": "لِنبنِ معًا السمعة التي يستحقّها ستوديوك.",

  // ═══════════ /personal-care-beauty-salons ═══════════
  "Dubai Personal Care & Beauty Salons | Multilingual Reputation Management with 90-Day Money-Back Guarantee | Reputation Experts":
    "صالونات العناية الشخصية والتجميل في دبي | إدارة سمعة متعدّدة اللغات مع ضمان استرداد الأموال خلال 90 يومًا | خبراء السمعة",
  "Dubai personal care and beauty salon reputation management": "إدارة السمعة الرقمية لصالونات العناية الشخصية والتجميل في دبي",
  "Dubai personal care and beauty salon reputation insight": "نظرة على واقع سمعة صالونات العناية الشخصية والتجميل في دبي",
  "Dubai’s only multilingual reputation team built for salons and beauty professionals.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات للصالونات وخبراء التجميل.",
  "The Dubai beauty salon reality": "واقع قطاع صالونات التجميل في دبي اليوم",
  "For many Dubai salons and beauty professionals,": "بالنسبة لكثير من الصالونات وخبراء التجميل في دبي،",
  "Dubai salons and barbers rated below": "صالونات وحلّاقو دبي ذوو التقييم الأقلّ من",
  "42% fewer new-client bookings": "تتلقّى حجوزات عملاء جدد أقلّ بنسبة 42%",
  "On a salon averaging 220 visits per month at AED 280 average ticket, that gap is worth roughly":
    "بالنسبة لصالون بمتوسط 220 زيارة شهريًا بمتوسط 280 درهمًا للزيارة، تُساوي هذه الفجوة تقريبًا",
  "in unrealised revenue from new clients, before counting the retention and referral value those same clients would have generated over time.":
    "من الإيرادات غير المحقّقة من العملاء الجدد، قبل احتساب قيمة الاحتفاظ والإحالة التي كان هؤلاء العملاء أنفسهم سيُولّدونها مع الوقت.",
  "poor reviews mean losing £3,000 to £30,000+ per year":
    "ضعف التقييمات يعني خسارة تتراوح من 3,000 إلى أكثر من 30,000 جنيه إسترليني سنويًا",
  "Source: Reputation Experts internal analysis, 31 Dubai hair, beauty and barber salons, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 31 صالون شعر وتجميل وحلاقة في دبي خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "From hair salons and barbers to beauty salons, nail bars, brow and lash studios and tattoo studios. We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your salon at the top of Google and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "من صالونات الشعر والحلاقة إلى صالونات التجميل ومراكز العناية بالأظافر وستوديوهات الحواجب والرموش وستوديوهات الوشم. نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع صالونك في صدارة بحث Google والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "In 2026, over 90% of Dubai clients check Google reviews before booking a salon, barber, nail bar or beauty treatment. Reputation directly drives revenue. A salon with a poor online reputation loses clients to the studio next door every single day, even when the stylists, the products and the location are equally strong. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع أكثر من 90% من العملاء في دبي على تقييمات Google قبل حجز صالون أو حلّاق أو مركز عناية بالأظافر أو جلسة تجميل. السمعة محرّك مباشر للإيرادات. والصالون ذو السمعة الرقمية الضعيفة يخسر عملاءه لصالح الصالون المجاور يوميًا، حتى وإن كان المصفّفون والمنتجات والموقع بالقوّة نفسها. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's personal care market, reputation directly drives revenue. 90% of clients check Google reviews before booking an appointment (unless existing clients). A salon sitting at lower star ratings loses clients to a competitor at a higher score every single day, even when the stylists, the products and the location are equally strong. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of new 5-star reviews that push it up, and ensuring your business appears prominently when potential clients search on Google, ask ChatGPT, or browse AI Overviews. The result is more clicks, more calls, and more booking enquiries, clients typically see a 30–50% increase in new client enquiries within the first three months.":
    "في سوق العناية الشخصية بدبي، السمعة محرّك مباشر للإيرادات. 90% من العملاء يطّلعون على تقييمات Google قبل حجز موعد (ما لم يكونوا عملاء سابقين). والصالون ذو التقييم الأقل يخسر عملاءه لصالح منافس بتقييم أعلى يوميًا، حتى وإن كان المصفّفون والمنتجات والموقع بالقوّة نفسها. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الجديدة بخمس نجوم ترفعه، ونضمن ظهور نشاطك بشكل بارز حين يبحث العملاء المحتملون على Google، أو يسألون ChatGPT، أو يتصفّحون إجابات AI Overview. والنتيجة: مزيد من النقرات، ومزيد من المكالمات، ومزيد من استفسارات الحجز — يحقّق عملاؤنا عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best hair salon near me\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific businesses. Reputation Experts strengthens your entire digital presence so your business is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your personal care or beauty business is featured in trusted media and reputable publications, something we specialise in, it creates the kind of authority signals that naturally improve how your business is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل صالون شعر قريب\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بأنشطة بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى يكون نشاطك في موقع أفضل بكثير ليثق به ذكاء Google ويوصي به. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين يظهر نشاطك في وسائل إعلام موثوقة ومنشورات مرجعية — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف يُفهَم نشاطك ويُوصى به من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my salon boost bookings and increase revenue?":
    "كيف يُساعد خبراء السمعة صالوني على زيادة الحجوزات والإيرادات؟",
  "How does Google's AI Overview affect my salon?": "كيف تؤثّر إجابات Google AI Overview على صالوني؟",
  "How long does it take to see results for my Dubai salon?": "كم من الوقت أحتاج حتى أرى نتائج فعلية لصالوني في دبي؟",
  "We also ensure your salon appears prominently when clients search on Google or ask ChatGPT for salon recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the markets that matter: GCC, UK, Russia, India, China and Europe. More new-client bookings, more package upgrades, and more repeat visits. Dubai salons typically see a 30 to 50% increase in new-client enquiries within the first three months.":
    "كما نضمن ظهور صالونك بشكل بارز حين يبحث العملاء على Google، أو يسألون ChatGPT عن توصيات الصالونات في دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأسواق التي تهمّك — دول الخليج، والمملكة المتحدة، وروسيا، والهند، والصين، وأوروبا. مزيد من حجوزات العملاء الجدد، ومزيد من ترقيات الباقات، ومزيد من الزيارات المتكرّرة. تحقّق صالونات دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "We monitor your Google Business Profile around the clock, alongside how your salon surfaces in Google AI Overviews and ChatGPT recommendations. The moment a harmful review appears, in any language, our team is alerted and we begin the removal process immediately. If a review cannot be taken down, we craft a professional response on your behalf in the right language, showing prospective clients that your salon takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business على مدار الساعة، إلى جانب كيفية ظهور صالونك في إجابات Google AI Overview وتوصيات ChatGPT. ولحظة ظهور تقييم مسيء، بأي لغة، يصل التنبيه إلى فريقنا ونبدأ إجراءات الإزالة فورًا. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للعملاء المحتملين أن صالونك يأخذ ملاحظاتهم بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "Real-time alerts whenever your salon is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة يُذكر فيها صالونك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications, all in one integrated service built specifically for Dubai hair, beauty, barber, nail and personal care salons. Every strategy is shaped around how Dubai clients actually search for and choose a salon online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا لصالونات الشعر والتجميل والحلاقة والأظافر والعناية الشخصية في دبي. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها العملاء في دبي فعليًا عن صالون ويختارونه على الإنترنت.",
  "We work across three phases. First, we clean up, removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen, building a steady flow of genuine 5-star reviews from your existing clients using follow-up systems timed around bookings, and publishing authoritative content that positions your business as a trusted name online. Third, we establish long-term authority, securing press coverage, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من عملائك الحاليين عبر أنظمة متابعة مدروسة التوقيت حول الحجوزات، وننشر محتوى مرجعيًا يُرسّخ مكانة نشاطك كاسم موثوق على الإنترنت. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join Dubai salons and beauty professionals who trust us to protect and grow their online presence.":
    "انضمّ إلى الصالونات وخبراء التجميل في دبي الذين يثقون بنا لحماية حضورهم الرقمي وتنميته.",
  "Let's build a reputation your salon deserves.": "لِنبنِ معًا السمعة التي يستحقّها صالونك.",

  // ═══════════ /home-services ═══════════
  "Dubai Home Services | AC, Plumbing, Electrical, Handyman, Painting, Carpentry, Pest Control & Pool Maintenance | Multilingual Reputation Management | Reputation Experts":
    "الخدمات المنزلية في دبي | تكييف، سباكة، كهرباء، صيانة عامة، دهان، نجارة، مكافحة حشرات، وصيانة المسابح | إدارة سمعة متعدّدة اللغات | خبراء السمعة",
  "Dubai home services reputation management": "إدارة السمعة الرقمية لشركات الخدمات المنزلية في دبي",
  "Dubai home services reputation insight": "نظرة على واقع سمعة قطاع الخدمات المنزلية في دبي",
  "Dubai’s only multilingual reputation team built for home services companies.":
    "الفريق الوحيد في دبي المتخصّص في إدارة السمعة متعدّدة اللغات لشركات الخدمات المنزلية.",
  "The Dubai home services reality": "واقع قطاع الخدمات المنزلية في دبي اليوم",
  "For many Dubai home services companies,": "بالنسبة لكثير من شركات الخدمات المنزلية في دبي،",
  "Dubai home service companies rated below": "شركات الخدمات المنزلية في دبي ذات التقييم الأقلّ من",
  "41% fewer new-customer jobs": "تتلقّى طلبات عملاء جدد أقلّ بنسبة 41%",
  "On a company running 320 jobs per month at AED 480 average ticket, that gap is worth roughly":
    "بالنسبة لشركة تُنفّذ 320 طلبًا شهريًا بمتوسط 480 درهمًا للطلب، تُساوي هذه الفجوة تقريبًا",
  "in unrealised service revenue, before counting the repeat-and- referral value of residents who would have made you their default handyman, AC technician or plumber.":
    "من إيرادات الخدمة غير المحقّقة، قبل احتساب قيمة التكرار والإحالة لسكّان كانوا سيجعلونك خيارهم الافتراضي للصيانة العامة أو فني التكييف أو السباك.",
  "poor reviews mean losing £2,000 to £100,000+ per year":
    "ضعف التقييمات يعني خسارة تتراوح من 2,000 إلى أكثر من 100,000 جنيه إسترليني سنويًا",
  "Source: Reputation Experts internal analysis, 33 Dubai home services companies covering AC, plumbing, electrical, handyman, painting, pest control and pool maintenance, 2025. Directional benchmark, not an audited statistic.":
    "المصدر: تحليل داخلي لخبراء السمعة، شمل 33 شركة خدمات منزلية في دبي تغطّي التكييف والسباكة والكهرباء والصيانة العامة والدهان ومكافحة الحشرات وصيانة المسابح، خلال 2025. مؤشر استرشادي وليس إحصاءً مدقّقًا.",
  "From AC servicing and plumbing to electrical, handyman, painting, carpentry, pest control, moving, landscaping, gardening and pool maintenance. We remove damaging reviews, generate authentic 5-star feedback in Arabic, English, Russian, Mandarin, German and French, and position your business at the top of Google and AI-driven search (Google AI Overviews and ChatGPT). Backed by a 90-day money-back guarantee. Hit your goals, or full refund, no questions.":
    "من صيانة التكييف والسباكة إلى الكهرباء والصيانة العامة والدهان والنجارة ومكافحة الحشرات والنقل وتنسيق الحدائق والبستنة وصيانة المسابح. نُزيل التقييمات المسيئة، ونُولّد تقييمات حقيقية بخمس نجوم بالعربية والإنجليزية والروسية والماندرين والألمانية والفرنسية، ونضع نشاطك في صدارة بحث Google والبحث المدفوع بالذكاء الاصطناعي (Google AI Overview و ChatGPT). كل ذلك مدعوم بضمان استرداد الأموال خلال 90 يومًا. حقّق أهدافك، أو استرد كامل ما دفعت، دون أي أسئلة.",
  "In 2026, over 90% of Dubai residents check Google reviews before booking an AC technician, plumber, electrician, handyman, painter or pest control company. Reputation directly drives revenue. A home services company with a poor online reputation loses jobs to the company next door every single day, even when the technicians, the response times and the pricing are equally strong. We close that gap by removing damaging reviews that drag your rating down and generating a consistent stream of authentic multilingual 5-star reviews that strengthen trust and push your rating up.":
    "في عام 2026، يطّلع أكثر من 90% من سكّان دبي على تقييمات Google قبل حجز فني تكييف أو سباك أو كهربائي أو فني صيانة عامة أو دهّان أو شركة مكافحة حشرات. السمعة محرّك مباشر للإيرادات. وشركة الخدمات المنزلية ذات السمعة الرقمية الضعيفة تخسر طلباتها لصالح الشركة المجاورة يوميًا، حتى وإن كان الفنيون وأوقات الاستجابة والأسعار بالقوّة نفسها. نسدّ هذه الفجوة بإزالة التقييمات المسيئة التي تسحب تقييمك إلى الأسفل، وبتوليد تدفّق منتظم من التقييمات الحقيقية متعدّدة اللغات بخمس نجوم، بما يُعزّز الثقة ويرفع تقييمك.",
  "In Dubai's home services market, reputation directly drives revenue. 90% of residents check Google reviews before booking a technician (unless existing clients). A company sitting at lower star ratings loses jobs to a competitor at a higher score every single day, even when the technicians, the response times and the pricing are equally strong. We close that gap by removing unfair reviews that drag your rating down, generating a consistent stream of new 5-star reviews that push it up, and ensuring your business appears prominently when potential customers search on Google, ask ChatGPT, or browse AI Overviews. The result is more clicks, more calls, and more job bookings, clients typically see a 30–50% increase in new customer enquiries within the first three months.":
    "في سوق الخدمات المنزلية بدبي، السمعة محرّك مباشر للإيرادات. 90% من السكّان يطّلعون على تقييمات Google قبل حجز فني (ما لم يكونوا عملاء سابقين). والشركة ذات التقييم الأقل تخسر طلباتها لصالح منافس بتقييم أعلى يوميًا، حتى وإن كان الفنيون وأوقات الاستجابة والأسعار بالقوّة نفسها. نسدّ هذه الفجوة من ثلاث جهات: نُزيل التقييمات غير العادلة التي تسحب تقييمك إلى الأسفل، ونُولّد تدفّقًا منتظمًا من التقييمات الجديدة بخمس نجوم ترفعه، ونضمن ظهور نشاطك بشكل بارز حين يبحث العملاء المحتملون على Google، أو يسألون ChatGPT، أو يتصفّحون إجابات AI Overview. والنتيجة: مزيد من النقرات، ومزيد من المكالمات، ومزيد من حجوزات الطلبات — يحقّق عملاؤنا عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "Google's AI Overviews now pull together information from reviews, your website, and third-party sources into a single AI-generated answer at the top of the search results. When someone searches for terms like \"best plumber near me\", Google no longer just shows a list of websites; it increasingly highlights and recommends specific businesses. Reputation Experts strengthens your entire digital presence so your business is in a far better position to be trusted and recommended by Google's AI. This includes improving your review profile, increasing rating strength and review volume, optimising trust signals across your web presence, and building authority through high-quality third-party coverage. When your company is featured in trusted lifestyle and property publications and reputable publications, something we specialise in, it creates the kind of authority signals that naturally improve how your company is understood and recommended by Google AI Overviews, ChatGPT, and other AI-driven discovery platforms.":
    "تجمع إجابات Google AI Overview اليوم المعلومات من التقييمات، ومن موقعك، ومن مصادر خارجية، في إجابة واحدة مُولَّدة بالذكاء الاصطناعي تتصدّر نتائج البحث. وحين يبحث أحدهم عن \"أفضل سبّاك قريب\"، لم يعد Google يكتفي بعرض قائمة مواقع؛ بل يُبرز ويوصي بأنشطة بعينها. يُعزّز خبراء السمعة حضورك الرقمي بكامله حتى يكون نشاطك في موقع أفضل بكثير ليثق به ذكاء Google ويوصي به. ويشمل ذلك تحسين ملف تقييماتك، ورفع قوّة التقييم وعدد التقييمات، وتحسين إشارات الثقة عبر حضورك الرقمي، وبناء المرجعية عبر تغطية خارجية عالية الجودة. وحين تظهر شركتك في منشورات نمط حياة وعقارات موثوقة ومنشورات مرجعية — وهو ما نتخصّص فيه — تتكوّن إشارات المرجعية التي تُحسّن طبيعيًا كيف تُفهَم شركتك ويُوصى بها من قِبل Google AI Overview و ChatGPT وسائر منصّات الاكتشاف المدفوعة بالذكاء الاصطناعي.",
  "How does Reputation Experts help my home services company boost jobs and increase revenue?":
    "كيف يُساعد خبراء السمعة شركتي للخدمات المنزلية على زيادة الطلبات والإيرادات؟",
  "How does Google's AI Overview affect my Dubai home services company?": "كيف تؤثّر إجابات Google AI Overview على شركتي للخدمات المنزلية في دبي؟",
  "How long does it take to see results for my Dubai home services company?": "كم من الوقت أحتاج حتى أرى نتائج فعلية لشركتي للخدمات المنزلية في دبي؟",
  "We also ensure your business appears prominently when residents search on Google or ask ChatGPT for home services recommendations in Dubai, including in Google AI Overviews. The result is more visibility in the neighbourhoods that matter: Marina, JBR, Downtown, Business Bay, Palm Jumeirah, Arabian Ranches, Damac Hills, JVC and beyond. More booked jobs, more repeat customers, and more referrals. Dubai home services companies typically see a 30 to 50% increase in new customer enquiries within the first three months.":
    "كما نضمن ظهور نشاطك بشكل بارز حين يبحث السكّان على Google، أو يسألون ChatGPT عن توصيات الخدمات المنزلية في دبي، بما في ذلك في إجابات Google AI Overview. والنتيجة: مزيد من الظهور في الأحياء التي تهمّك — المارينا، و JBR، ووسط المدينة، والخليج التجاري، ونخلة جميرا، ومرابع العرب، وداماك هيلز، و JVC وما بعدها. مزيد من الطلبات المحجوزة، ومزيد من العملاء المتكرّرين، ومزيد من الإحالات. تحقّق شركات الخدمات المنزلية في دبي عادةً ارتفاعًا من 30% إلى 50% في استفسارات العملاء الجدد خلال أوّل ثلاثة أشهر.",
  "We monitor your Google Business Profile and other platforms around the clock. The moment a new harmful review appears, our team is alerted and processes the removal, if the review can not be taken down, we craft a professional response on your behalf in the right language, showing prospective customers that your company takes feedback seriously. You're never caught off guard by a review again.":
    "نراقب ملفك على Google Business والمنصّات الأخرى على مدار الساعة. لحظة ظهور تقييم مسيء جديد، يصل التنبيه إلى فريقنا ونباشر بإجراءات الإزالة. وإن تعذّر إزالة التقييم، نصوغ نيابةً عنك ردًّا احترافيًا باللغة المناسبة، يُظهر للعملاء المحتملين أن شركتك تأخذ ملاحظاتهم بجدّية. لن تُفاجأ بأي تقييم بعد اليوم.",
  "Real-time alerts whenever your company is mentioned online. New review? We notify you. Negative article? We flag it. So you’re never caught off guard again.":
    "تنبيهات فورية في كل مرّة تُذكر فيها شركتك على الإنترنت. تقييم جديد؟ نُخبرك. مقال سلبي؟ نرفع لك التنبيه. لتبقى دائمًا على اطّلاع، دون أي مفاجآت.",
  "Our approach brings together review management, reputation building, Google AI Overview optimisation, ChatGPT recommendation positioning, and major online media publications, all in one integrated service built specifically for Dubai AC, plumbing, electrical, handyman, painting, pest control, pool and home services companies. Every strategy is shaped around how Dubai residents actually search for and choose a home services company online.":
    "تجمع منهجيّتنا بين إدارة التقييمات، وبناء السمعة، وتحسين الظهور في Google AI Overview، وترتيبك في توصيات ChatGPT، والظهور في كبرى المنابر الإعلامية على الإنترنت — كل ذلك في خدمة متكاملة مصمّمة خصيصًا لشركات التكييف والسباكة والكهرباء والصيانة العامة والدهان ومكافحة الحشرات والمسابح والخدمات المنزلية في دبي. وكل استراتيجية مبنيّة حول الطريقة التي يبحث بها سكّان دبي فعليًا عن شركة خدمات منزلية ويختارونها على الإنترنت.",
  "We work across three phases. First, we clean up, removing policy-violating reviews, suppressing negative search results, and fixing gaps in your Google Business Profile. Second, we strengthen, building a steady flow of genuine 5-star reviews from your existing customers using follow-up systems timed around job enquiries, and publishing authoritative content that positions your business as a trusted name online. Third, we establish long-term authority, securing press coverage, optimising for Google AI Overviews and ChatGPT recommendations, and providing ongoing monitoring so your reputation stays protected month after month.":
    "نعمل على ثلاث مراحل. أولًا، التنظيف: نُزيل التقييمات المخالفة لسياسات المنصات، ونُخفي نتائج البحث السلبية، ونعالج الثغرات في ملف نشاطك على Google. ثانيًا، التعزيز: نبني تدفّقًا منتظمًا من التقييمات الحقيقية بخمس نجوم من عملائك الحاليين عبر أنظمة متابعة مدروسة التوقيت حول طلبات الخدمة، وننشر محتوى مرجعيًا يُرسّخ مكانة نشاطك كاسم موثوق على الإنترنت. ثالثًا، ترسيخ المرجعية على المدى البعيد: نؤمّن تغطيات صحفية، ونُحسّن ظهورك في Google AI Overview وتوصيات ChatGPT، ونوفّر مراقبة مستمرة لتبقى سمعتك محميّة شهرًا بعد شهر.",
  "Join home service professionals across the UAE who trust us to protect and grow their online presence.":
    "انضمّ إلى مزوّدي الخدمات المنزلية في كافة الإمارات الذين يثقون بنا لحماية حضورهم الرقمي وتنميته.",
  "Let's build a reputation your company deserves.": "لِنبنِ معًا السمعة التي تستحقّها شركتك.",
};
