// Tenth pass: /reviews and /ai-search FAQ + section paragraph variants
// after another round of copy edits on the live pages. Many endings were
// trimmed or rephrased so the previous dictionary keys no longer matched.

export const AR_DICT_REVIEWS_V3: Record<string, string> = {

  // ─── /reviews — section paragraph variants ───────────────────────────────
  "Reputation damage happens in the hours between when something bad goes live and when anyone on your team notices. Our monitoring engine flags it the moment it appears and triggers the right response — dispute, takedown, or counter-narrative — before it spreads.":
    "ضرر السمعة يحدث في الساعات الفاصلة بين ظهور المحتوى السيئ وبين انتباه فريقك له. محرّك المراقبة لدينا يرصده فور ظهوره ويُطلق الاستجابة المناسبة — اعتراض، أو طلب إزالة، أو محتوى مضاد — قبل أن ينتشر.",
  "Most businesses notice the symptoms first, fewer enquiries, lower marketing ROI, dropping organic traffic, long before they trace it back to reviews. By the time the pattern is obvious, six to twelve months of revenue have already gone.":
    "تلاحظ معظم الشركات الأعراض أوّلًا — تراجع الاستفسارات، وضعف عائد التسويق، وانخفاض الزيارات العضوية — قبل وقت طويل من ربط ذلك بضعف ملف التقييمات. وبحلول الوقت الذي يتّضح فيه النمط، تكون من ستة إلى اثني عشر شهرًا من الإيرادات قد ضاعت بالفعل.",
  "A prospect sees your ad, clicks the location, sees a thin or negative review profile, and chooses a competitor. You paid for the impression, the click and the bid premium, and the conversion went next door. Every marketing dirham you spend is mid-funnel; the reviews are the funnel's last gate.":
    "العميل المحتمل يرى إعلانك، ينقر على العنوان، يجد ملف تقييمات ضعيفًا أو سلبيًا، فيختار منافسك. أنت دفعت ثمن الظهور، والنقرة، وعلاوة المزايدة — وذهب التحويل إلى الجوار. كل درهم تُنفقه على التسويق يقع في منتصف القمع، والتقييمات هي البوّابة الأخيرة فيه.",
  "Maps users skim ratings and review count before they read anything else. A low rating or fewer than 20 reviews drops your click-through rate to a fraction of what it should be, even when you outrank competitors on map position.":
    "مستخدمو الخرائط يُلقون نظرة سريعة على التقييم وعدد المراجعات قبل أي شيء آخر. التقييم المنخفض أو أقلّ من 20 تقييمًا يُسقط نسبة النقرات إلى جزء بسيط ممّا يجب أن تكون، حتى وإن كنت تتقدّم منافسيك في موقع الخريطة.",
  "ChatGPT, Google AI Overview, Perplexity and Gemini weight review depth, recency and sentiment heavily. A weak profile means the AI suggests a competitor by name, and you never appear in the answer at all. AI traffic is the fastest-growing top-of-funnel source in Dubai right now.":
    "تعتمد ChatGPT و Google AI Overview و Perplexity و Gemini بشكل كبير على عمق التقييمات وحداثتها واتجاه المشاعر. الملف الضعيف يعني أن الذكاء الاصطناعي يُسمّي منافسك في الإجابة، وأنت لا تظهر فيها إطلاقًا. الزيارات القادمة من الذكاء الاصطناعي هي اليوم أسرع مصدر نموًا في أعلى قمع المبيعات بدبي.",
  "We run authentic review growth campaigns across nearly 200 platforms, dispute and remove harmful content, optimise every listing with the structured-data markup search engines and AI engines actually read, and back the work with a written 90-day score guarantee.":
    "نُنفّذ حملات حقيقية لنمو التقييمات على ما يقارب 200 منصّة، ونعترض على المحتوى المسيء ونعمل على إزالته، ونُحسّن بيانات كل منصّة بالبيانات المنظَّمة التي تقرؤها محركات البحث والذكاء الاصطناعي فعليًا، وندعم العمل بضمان كتابي لتحسّن التقييم خلال 90 يومًا.",
  "On your own website we insert the JSON-LD schema markup (LocalBusiness, Service, FAQ, Review) that Google's Local Pack and AI Overview parsers rely on to rank and cite a business. Most competitor sites have none of this.":
    "نُضيف على موقعك بيانات JSON-LD الوصفية (LocalBusiness و Service و FAQ و Review) التي تعتمد عليها محرّكات Local Pack في Google و AI Overview في ترتيب الأنشطة والاستشهاد بها. معظم مواقع المنافسين لا تتضمّن أيًّا من ذلك.",

  // ─── /reviews FAQ — full Q&A answers in current phrasing ────────────────
  "Either. Most clients keep their ads and content agency, and use us as the reputation layer underneath. Some hand us the full presence — listings, reviews, schema, AI search, PR — and we coordinate with their internal marketing. There's no required setup; the work plugs in beside whatever you already have.":
    "كلاهما ممكن. معظم العملاء يحتفظون بوكالة الإعلانات والمحتوى لديهم، ويستعينون بنا كطبقة سمعة تحتها. والبعض يُسلّمنا الحضور الرقمي كاملًا — بيانات النشاط، التقييمات، البيانات المنظَّمة، البحث الذكي، العلاقات العامة — ونتولّى التنسيق مع فريقه التسويقي الداخلي. لا يوجد إعداد إلزامي مسبق؛ العمل ينضمّ إلى ما لديك دون أن يُربك ما هو قائم.",
  "We do not gate reviews — that breaches platform policy. What we do is route the request differently: an unhappy customer who completes our follow-up gets a private recovery flow first (your team gets a chance to fix the issue before any public review is invited), while a satisfied customer goes straight to the public review platform. This is policy-compliant and improves both your average rating and your customer relationships.":
    "نحن لا نمنع العملاء من ترك التقييمات — فذلك يخالف سياسة المنصات. ما نفعله هو توجيه الطلب بشكل مختلف: العميل غير الراضي الذي يُكمل استبيان المتابعة يدخل أوّلًا في مسار خاص لاستعادة رضاه (يحصل فريقك على فرصة لمعالجة المشكلة قبل أن يُطلب منه ترك تقييم علني)، أمّا العميل الراضي فينتقل مباشرةً إلى منصّة التقييم العامة. هذا النهج ممتثل لسياسات المنصات، ويُحسّن في الوقت ذاته معدّل تقييمك العام وعلاقتك بعملائك.",
  "No, ever. Fake reviews are a fast way to get a business permanently delisted from Google and Trustpilot, and they show up in AI sentiment analysis as obviously inauthentic. Everything we do is built on real customers leaving real opinions at the right moment — timed, prompted and routed correctly, but never invented.":
    "لا، أبدًا. التقييمات المزيّفة هي أسرع طريق لشطب نشاطك نهائيًا من Google و Trustpilot، كما أنها تظهر في تحليل المشاعر بالذكاء الاصطناعي كتقييمات غير حقيقية بشكل واضح. كل ما نقوم به مبنيّ على عملاء حقيقيين يتركون آراءهم الحقيقية في التوقيت المناسب — مدروسة التوقيت، ومُحفَّزة، ومُوجَّهة بطريقة سليمة، لكنها لم تُخترع أبدًا.",
  "Most clients see meaningful score movement and visible review velocity inside the first 30 days. By day 60, AI engines and Google Maps typically begin re-ranking the business upward. The full 90 days is needed for the harder lifts — moving an established score by 0.3 or more — because authentic reviews have to be earned at the speed your real customers can leave them.":
    "يلاحظ معظم العملاء تحرّكًا فعليًا في التقييم وارتفاعًا واضحًا في وتيرة التقييمات خلال أوّل 30 يومًا. وبحلول اليوم الستين، تبدأ محرّكات الذكاء الاصطناعي وخرائط Google عادةً بإعادة ترتيب النشاط إلى الأعلى. أمّا الـ 90 يومًا كاملةً فنحتاجها للقفزات الأصعب — مثل رفع تقييم راسخ بمقدار 0.3 أو أكثر — لأن التقييمات الحقيقية يجب أن تُكتسب بإيقاع يستطيع عملاؤك الفعليّون تركها به.",
  "Yes — directly. AI engines treat review depth, recency and sentiment as primary signals when deciding which businesses to name in an answer. A business with 600 fresh reviews above 4.6 stars is dramatically more likely to be cited than a competitor with 80 reviews at 4.1. The work on this page feeds straight into the work on /ai-search: reviews are the highest-weight input AI engines look at when generating recommendations.":
    "نعم — وبشكل مباشر. تتعامل محرّكات الذكاء الاصطناعي مع عمق التقييمات وحداثتها واتّجاه مشاعرها كإشارات رئيسية عند اختيار الأسماء التي تُذكر في الإجابات. الشركة التي لديها 600 تقييم حديث بمعدّل أعلى من 4.6 نجوم تحظى بفرصة أكبر بكثير في الاستشهاد بها مقارنةً بمنافس لديه 80 تقييمًا عند 4.1. والعمل على هذه الصفحة يصبّ مباشرةً في عمل صفحة /ai-search: التقييمات هي الإشارة الأعلى وزنًا التي تعتمد عليها محرّكات الذكاء الاصطناعي عند توليد التوصيات.",
  "Google, Apple, Bing and category-specific directories all read structured data — JSON-LD schema markup like LocalBusiness, Service, FAQ and Review — to understand and rank a business. Most competitor sites have none of it. We audit your Google Business Profile, Apple Business Connect, Bing Places and the long tail of directories so every detail is accurate, consistent and complete, then insert the right schema on your own website so search engines and AI engines can read your business correctly. It is one of the highest-leverage SEO moves available and most agencies skip it.":
    "Google و Apple و Bing وأدلة الفئات المتخصّصة، كلها تقرأ البيانات المنظَّمة — تعليمات JSON-LD مثل LocalBusiness و Service و FAQ و Review — لتفهم ترتيب الأنشطة. معظم مواقع المنافسين لا تطبّق أيًّا منها. نحن نُجري تدقيقًا شاملًا لبياناتك على Google Business Profile و Apple Business Connect و Bing Places والمنصّات المتخصّصة، حتى يكون كل تفصيل دقيقًا ومتّسقًا ومكتملًا، ثم نُضيف الـ schema الصحيح على موقعك حتى تتمكّن محركات البحث والذكاء الاصطناعي من قراءة نشاطك بشكل صحيح. وهذه واحدة من أعلى تحرّكات تحسين البحث أثرًا، ومعظم الوكالات تتجاوزها.",
  "Before we start we agree a written target — typically the move from your current average star rating to a higher one (e.g. 4.2 to 4.6), plus a minimum number of fresh authentic reviews per location. If we don't hit those numbers by day 90, the engagement keeps running at no additional cost until we do. The guarantee is anchored to specific written metrics, not vague effort.":
    "قبل أن نبدأ نتفق خطيًا على هدف محدّد — عادةً الانتقال من معدل النجوم الحالي إلى معدل أعلى (مثلًا من 4.2 إلى 4.6)، مع حدّ أدنى من التقييمات الحقيقية الجديدة لكل فرع. إن لم نصل إلى هذه الأرقام بحلول اليوم التسعين، يستمرّ التعاقد دون أي تكلفة إضافية حتى نصل إليها. الضمان مرتبط بمؤشّرات كتابية محدّدة، لا بمجرّد جهد عام.",
  "Yes. For posts that cross into defamation or impersonate your business, we coordinate the formal takedown notices each platform requires. For competitors or scraper sites using your photos, branding or treatment results without permission, we file DMCA and Google copyright notices that get the assets removed at source. Where a matter needs to go beyond platform processes we brief your solicitor with the evidence pack ready.":
    "نعم. بالنسبة للمنشورات التي تصل إلى حدّ التشهير أو انتحال هوية نشاطك، نتولّى تنسيق طلبات الإزالة الرسمية وفق متطلبات كل منصّة. أمّا المنافسون أو المواقع التي تستخدم صورك أو هويتك أو نتائج أعمالك دون إذن، فنرفع طلبات DMCA وإشعارات حقوق النشر إلى Google لإزالة هذه الأصول من مصدرها. وحين يستلزم الأمر تجاوز إجراءات المنصّات، نُجهّز ملف الأدلة كاملًا لمحاميك ليكون جاهزًا للتحرّك.",
  "We successfully remove around 78% of the reviews our clients flag. Anything that breaches the platform's policy — fake, off-topic, conflict-of-interest, harassment, hate speech, content from people who were never customers — is grounds for dispute. We file the request, follow it through, and re-file every time a removed review reappears. For reviews that don't meet the policy bar, we focus on burying them under a steady flow of authentic positive reviews so the platform's algorithm ranks them lower in the visible feed.":
    "نُزيل بنجاح نحو 78% من التقييمات التي يرفعها لنا عملاؤنا. كل ما يخالف سياسات المنصّات — مزيّف، خارج الموضوع، تعارض مصالح، تحرّش، خطاب كراهية، أو محتوى من أشخاص لم يكونوا عملاء أصلًا — يُشكّل أساسًا للاعتراض. نرفع الطلب، ونتابعه حتى نهايته، ونُعيد رفعه في كل مرّة يعود فيها التقييم الذي أُزيل إلى الظهور. أمّا التقييمات التي لا تستوفي شروط سياسة المنصّة، فنُركّز على إخفائها تحت تدفّق منتظم من التقييمات الإيجابية الحقيقية، حتى تُرتّبها خوارزمية المنصّة في أسفل التغذية الظاهرة للعميل.",
  "Nearly 200 in total, but the work concentrates on the eight to twelve that matter most for your category. Every business gets Google, Trustpilot, Facebook and Apple as a baseline; from there we layer in the trade-specific platforms — Tripadvisor and Booking.com for hospitality, Doctify and WhatClinic for healthcare, Yell and Bark for home services, Tradesy and Houzz for trades, and so on. The platform identifies the highest-leverage sites for your specific niche and routes review requests to the ones that move bookings.":
    "ما يقارب 200 منصّة إجمالًا، لكن العمل يتركّز على ثماني إلى اثنتي عشرة منصّة هي الأهمّ لقطاعك. كل نشاط يحصل على Google و Trustpilot و Facebook و Apple كأساس، ثم نُضيف فوقها المنصّات المتخصّصة بقطاعك — Tripadvisor و Booking.com للضيافة، و Doctify و WhatClinic للرعاية الصحية، و Yell و Bark للخدمات المنزلية، و Tradesy و Houzz للمهن الحرفية، وهكذا. تُحدّد المنصّة المواقع الأعلى أثرًا في تخصّصك بالذات، وتوجّه طلبات التقييم إلى تلك التي تُحرّك الحجوزات فعلًا.",

  // ─── /ai-search FAQ — current variants ───────────────────────────────────
  "Google Business Profile updates per location, multilingual review request campaigns timed to your operational rhythm (check-out, treatment completion, project handover, key handover), on-site service-page rewrites with the right schema, location-specific FAQ blocks that match high-intent Dubai queries, location-specific landing pages, multilingual review responses, dispute filings against policy-violating reviews, and PR placements in international and Middle East trade and consumer publications. You approve the work; our team and the platform execute.":
    "تحديثات لملف Google Business لكل فرع، وحملات طلب تقييم متعدّدة اللغات بتوقيتات إيقاع عملك (المغادرة، إنجاز العلاج، تسليم المشروع، تسليم المفاتيح)، وإعادة كتابة صفحات الخدمات على موقعك مع schema الصحيح، وكتل أسئلة وأجوبة خاصة بكل فرع تُطابق استعلامات دبي عالية الأهمية، وصفحات هبوط خاصة بكل فرع، وردود متعدّدة اللغات على التقييمات، ورفع اعتراضات على التقييمات المخالفة لسياسات المنصّات، وظهور تحريري في كبرى المنشورات الدولية ومنشورات قطاع التجارة والمستهلك في الشرق الأوسط. أنت تمنح الموافقة، وفريقنا والمنصّة يتولّيان التنفيذ.",
  "Yes. For every tracked query, the dashboard captures the full AI answer, the cited sources, and the reasoning trace where available. You see verbatim how Gemini described you, which sentence in which review it likely drew from, and which competitor it positioned ahead of you. Your dedicated reputation manager walks you through this every month and turns it into the prioritised fix list for the following 30 days.":
    "نعم. لكل استعلام مُتتبَّع، تلتقط اللوحة الإجابة الكاملة من الذكاء الاصطناعي، والمصادر المستشهد بها، وتسلسل الاستدلال حيث يكون متاحًا. ترى حرفيًا كيف وصفك Gemini، وأيّ جملة من أي تقييم استلهم منها على الأرجح، وأيّ منافس وضعه في موقع متقدّم عليك. ويستعرض معك مدير سمعتك المخصّص هذه الرؤى شهريًا، ويحوّلها إلى قائمة الإصلاحات ذات الأولوية للثلاثين يومًا القادمة.",
  "Yes. The dashboard reports weekly share of voice per engine, per location, per language, with trend lines back to your baseline week. You can pin specific high-intent queries to a watchlist, see citation lifts per source, and export anything to monthly stakeholder reports. The 90-day money-back guarantee is anchored to the metrics you and Reputation Experts agree on at the start of the engagement, in writing.":
    "نعم. تُقدّم اللوحة تقارير أسبوعية عن حصّة الذكر لكل محرّك ولكل فرع ولكل لغة، مع خطوط بيانية تعود إلى أسبوع البدء. يمكنك تثبيت استعلامات عالية الأهمية في قائمة متابعة، ورؤية ارتفاع الاستشهادات حسب كل مصدر، وتصدير أي شيء إلى تقارير شهرية لأصحاب المصلحة. وضمان استرداد الأموال خلال 90 يومًا مرتبط بالمؤشّرات التي تتّفق عليها مع خبراء السمعة في بداية التعاقد، خطيًا.",
};
