// Twelfth pass: 8 more /ai-search FAQ + section variants. Page copy
// edited again with new endings — each prior variant kept in dict so no
// regression if reverted.

export const AR_DICT_AI_SEARCH_V4: Record<string, string> = {

  // 1. What is AI search visibility?
  "It is how often your Dubai business appears, gets named or gets cited when AI search engines (Google AI Overview, ChatGPT, Perplexity, Gemini) generate an answer. Classic SEO ranks pages; AI search visibility ranks businesses. The user sees one answer at the top of the page naming two or three companies. Reputation Experts measures and lifts your share of those answers across every high-intent Dubai query in your category, weekly, in every language your customers search in.":
    "هو عدد المرّات التي يظهر فيها نشاطك في دبي، أو يُذكَر اسمه، أو يُستشهد به، عندما تُولّد محرّكات البحث بالذكاء الاصطناعي (Google AI Overview و ChatGPT و Perplexity و Gemini) إجابة ما. تحسين محركات البحث التقليدي يُرتّب الصفحات، أمّا الظهور في البحث الذكي فيُرتّب الأنشطة التجارية ذاتها. يرى المستخدم إجابة واحدة في صدر الصفحة تُسمّي شركتين أو ثلاثًا. يقيس خبراء السمعة حصّتك من تلك الإجابات ويرفعها عبر كل استعلام دبيّ عالي الأهمية في فئتك، أسبوعيًا، وبكل لغة يبحث بها عملاؤك.",

  // 2. How does Reputation Experts track mentions...?
  "Our team runs your high-intent Dubai queries against every major AI search engine on a recurring schedule, captures the full answer text, parses out which businesses are named and which sources are cited, and aggregates the data into a single dashboard. You see your share of voice per engine, per query, per location, in every language we monitor. The work is delivered as a monthly report and reviewed with a dedicated reputation manager. The underlying technology is the Birdeye platform we white-label as your reseller in the UAE.":
    "يُجري فريقنا استعلاماتك عالية الأهمية في دبي على كل محرّكات البحث الذكي الكبرى وفق جدول دوري، يلتقط نصّ الإجابة الكامل، ويستخرج أسماء الأنشطة المذكورة والمصادر المستشهد بها، ويُجمّع البيانات في لوحة واحدة. ترى حصّتك من الذكر لكل محرّك ولكل استعلام ولكل فرع، بكل لغة نراقبها. يصلك العمل في تقرير شهري، تستعرضه معك مديرة سمعتك المخصّصة. والتقنية الأساسية المستخدَمة هي منصّة Birdeye التي نوزّعها بعلامتك في الإمارات.",

  // 3. What are citations and why do they matter? (new shorter variant)
  "Citations are the third-party sources an AI engine names when generating an answer. For a Dubai hotel, that might be Condé Nast Traveller Middle East, Hotelier Middle East or Khaleej Times. For a Dubai brokerage, Time Out Dubai or Gulf News. AI engines are dramatically more likely to recommend a business that appears in the sources they already trust. We map the citation landscape for your category, identify which sources matter most to each AI engine, and earn your brand placements there.":
    "الاستشهادات هي المصادر الخارجية التي يذكرها محرّك الذكاء الاصطناعي عند توليد الإجابة. لفندق في دبي قد تكون: Condé Nast Traveller Middle East، أو Hotelier Middle East، أو الخليج تايمز. ولمكتب عقارات في دبي قد تكون: Time Out Dubai، أو Gulf News. تميل محرّكات الذكاء الاصطناعي بشكل لافت إلى التوصية بالأنشطة التي تظهر في المصادر التي تثق بها أصلًا. نرسم لك خريطة الاستشهادات في فئتك، ونحدّد أي المصادر هي الأهمّ لكل محرّك، ونؤمّن لعلامتك ظهورًا فيها.",

  // 4. How can Reputation Experts help me rank higher in AI search? (new variant)
  "By engineering all four signals AI engines weight: review depth and recency, multilingual coverage (especially Arabic, English, Russian and Mandarin for Dubai), third-party citation authority and structured-data clarity. We start every engagement with a free 7-page audit of how each AI engine currently sees your business, run the fixes prioritised by expected visibility lift, and report weekly. If we do not hit the written goals in 90 days, you receive a full refund of every dirham paid.":
    "من خلال هندسة الإشارات الأربع التي تعتمدها محرّكات الذكاء الاصطناعي: عمق التقييمات وحداثتها، والتغطية المتعدّدة اللغات (لا سيّما العربية والإنجليزية والروسية والماندرين لجمهور دبي)، ومرجعية الاستشهادات من جهات خارجية، ووضوح البيانات المنظَّمة. نبدأ كل تعاقد بتدقيق مجاني من 7 صفحات لكيفية رؤية كل محرّك لنشاطك حاليًا، ثم ننفّذ الإصلاحات مرتّبةً وفق أكبر أثر متوقّع على ظهورك، ونرفع لك تقريرًا أسبوعيًا. وإن لم نحقّق الأهداف المكتوبة خلال 90 يومًا، تسترد كامل ما دفعت، درهمًا درهمًا.",

  // 5. How do AI engines decide which businesses to recommend? (new variant)
  "Each engine has its own ranking model and they do not all weight things identically, but in practice four signals consistently separate cited businesses from ignored ones: a steady cadence of authentic recent reviews in the languages the searcher uses, a citation footprint across trusted third-party sources, a complete and consistent business profile across Google, Apple and Bing, and topical clarity on your own website that matches the query intent. We work on all four, in parallel, in the order that moves your visibility fastest.":
    "لكل محرّك نموذجه الخاص في الترتيب، وهي لا تُعطي الإشارات الوزن ذاته، لكن أربع إشارات هي ما يُفرّق عمليًا بين الأنشطة المستشهد بها والمتجاهلة: تدفّق منتظم من التقييمات الحقيقية الحديثة باللغات التي يستخدمها الباحث، وبصمة استشهادات في المصادر الخارجية الموثوقة، وملف نشاط مكتمل ومتّسق عبر Google و Apple و Bing، ووضوح موضوعي على موقعك يُطابق نية الاستعلام. نشتغل على الإشارات الأربع كلها بالتوازي، بالترتيب الذي يُحرّك ظهورك بأسرع شكل.",

  // 6. Does Reputation Experts work for multi-location brands? (new variant)
  "Yes, and this is exactly what we are built for. A Dubai hotel group with properties in Marina, Downtown and Palm Jumeirah, or a clinic group with branches in DIFC, JLT and Business Bay, gets per-location AI visibility tracking, per-location competitor benchmarks, and per-location execution. Each location has its own review profile, citation landscape and competitor set, so the work has to be done location-by-location. The platform makes that scalable.":
    "نعم، وهذا هو ما صُمّمنا لأجله بالضبط. مجموعة فنادق في دبي لها فروع في المارينا ووسط المدينة ونخلة جميرا، أو مجموعة عيادات لها فروع في DIFC و JLT والخليج التجاري، تحصل على تتبّع لظهور كل فرع في الذكاء الاصطناعي، ومقارنات تنافسية لكل فرع، وتنفيذ خاص بكل فرع. لكل فرع ملف تقييمات خاص، وخريطة استشهادات خاصة، ومجموعة منافسين خاصة، ولهذا يجب أن يجري العمل فرعًا بفرع. والمنصّة هي ما يجعل ذلك قابلًا للتوسّع.",

  // 7. Why do multi-location brands specifically need a purpose-built tool? (new variant)
  "Because AI engines build a separate mental model of each location. What works for your flagship in Downtown will not transfer to your branch in Mirdif. Each location has its own review profile in its own language mix, its own competitor set, its own citation context. Without per-location tracking and per-location work, you fix the one branch that already worked and starve the ten that did not. Reputation Experts gives you visibility and execution at the location level by default.":
    "لأن محرّكات الذكاء الاصطناعي تبني نموذجًا ذهنيًا مستقلًّا لكل فرع. ما ينجح في فرعك الرئيسي بوسط المدينة لا ينتقل بالضرورة إلى فرعك في مردف. لكل فرع ملف تقييمات خاص بمزيج لغته، ومجموعة منافسين خاصة، وسياق استشهادات خاص. ومن دون تتبّع وعمل على مستوى الفرع، ينتهي بك الأمر إلى تحسين الفرع الذي كان جيّدًا أصلًا، وحرمان العشرة الباقين. مع خبراء السمعة، تحصل على الظهور والتنفيذ على مستوى الفرع بشكل افتراضي.",

  // 8. What types of Dubai businesses benefit most? (new variant with verticals list)
  "Any business where the customer journey starts with a search query that has commercial intent. Hospitality and dining are the biggest because international visitors plan from abroad and rely on AI to triage choices. Healthcare and aesthetic clinics, real estate brokerages, financial and professional services, automotive showrooms, car rental, home services, cleaning, fitness and spa, salons, and entertainment all see meaningful AI traffic share. We have dedicated solutions for each of these verticals on this site.":
    "أي نشاط تجاري يبدأ فيه مسار العميل باستعلام بحث ذي نيّة شرائية. الضيافة والمطاعم في المقدّمة، لأن الزوار الدوليين يخطّطون من الخارج ويعتمدون على الذكاء الاصطناعي لفرز خياراتهم. كما تشهد عيادات الرعاية الصحية والتجميل، ومكاتب العقارات، والخدمات المالية والمهنية، ومعارض السيارات، وتأجير السيارات، والخدمات المنزلية، والتنظيف، واللياقة والسبا، وصالونات التجميل، والترفيه، حصصًا حقيقية من زيارات الذكاء الاصطناعي. لدينا حلول مخصّصة لكل قطاع منها على هذا الموقع.",
};
