"use client";

import React, { useState } from "react";

const FAQ = [
  {
    q: "What is AI search visibility?",
    a: "It is how often your business appears, gets named or gets cited in the answers generated by AI search engines like Google AI Overview, ChatGPT, Perplexity and Gemini. Unlike classic SEO, which ranks pages, AI search visibility ranks businesses. The user sees one answer at the top of the page that names two or three companies. Visibility is the share of times your business is one of them.",
  },
  {
    q: "How does Search AI track mentions on ChatGPT, Gemini and Perplexity?",
    a: "It runs the same set of high-intent Dubai queries against each AI engine on a recurring schedule, captures the full answer text, parses out which businesses are named and which sources are cited, and aggregates the data over time. You get a single dashboard showing your share of voice per engine, per query, per location, with trend lines and the ability to drill into the exact answer that named or skipped you.",
  },
  {
    q: "How is Search AI different from generic GEO or SEO tools?",
    a: "Classic SEO tools rank pages against the ten blue links. GEO (Generative Engine Optimisation) tools track keywords against AI engines but stop at reporting. Search AI both tracks and acts: when it detects a gap, an agent pushes the fix to the system where the AI is reading from. That includes Google Business Profile updates, Apple Business Connect, Bing Places, multilingual review generation and on-site content updates timed to how each AI re-crawls.",
  },
  {
    q: "What are citations and why do they matter?",
    a: "Citations are the third-party sources an AI engine names when generating an answer. If ChatGPT recommends a Dubai clinic and cites Khaleej Times and Condé Nast Traveller Middle East, those are the citation sources. The AI is far more likely to recommend a business that appears in the sources it already trusts. Search AI maps which sources each engine cites most for your category and helps your brand earn placements there.",
  },
  {
    q: "How can Search AI help me rank higher in AI search?",
    a: "By engineering all four signals AI engines weight: review depth and recency, multilingual coverage (especially Arabic, English, Russian and Mandarin for Dubai), third-party citation authority, and structured data clarity. The platform diagnoses where your business is underread or skipped, agents execute the fixes, and the dashboard tracks whether your share of voice climbs in the engines and queries that matter to you.",
  },
  {
    q: "Does Search AI work for multi-location brands?",
    a: "Yes, and that is the use case it is built for. A Dubai hotel group with properties in Marina, Downtown and Palm Jumeirah, or a clinic group with branches in DIFC, JLT and Business Bay, can see AI visibility per location, per AI engine, per language, and direct agent activity to the locations that are lagging. You can also benchmark each location against its specific local competitors rather than the global brand only.",
  },
  {
    q: "Why do multi-location brands specifically need a purpose-built AI search tool?",
    a: "Because AI engines build a model of each location separately, and what works for your flagship in Downtown will not necessarily transfer to your branch in Mirdif. Each location has its own review profile, its own competitor set, its own citation context. Without per-location tracking and per-location agents, you fix the one branch that already worked and starve the ten that did not. Search AI gives you visibility and execution at the location level, by default.",
  },
  {
    q: "What kind of insights does Search AI provide?",
    a: "Where you appear and where you do not, per AI engine and per location. Which queries name you and which name your competitors. Which third-party sources the AI is citing for your category. How AI describes your business and which themes recur. Which fields of your Google Business Profile, Apple Business Connect and Bing Places are inconsistent across engines. And a prioritised list of fixes ranked by expected visibility lift.",
  },
  {
    q: "Why do certain locations appear in AI results while others do not?",
    a: "AI engines weight review depth, recency, language coverage and citation authority per location. A location with 600 English reviews and zero Arabic reviews looks to the AI like a business that only serves English speakers, and gets demoted for Arabic queries. A location featured once in Khaleej Times has citation authority a sister location without coverage does not. The fix is location-by-location, which is what the agents handle.",
  },
  {
    q: "How do AI engines actually decide which businesses to recommend?",
    a: "Each engine has its own ranking model and they do not all weight the same things identically, but in practice four signals consistently separate cited businesses from ignored ones: a steady cadence of authentic recent reviews in the languages the searcher uses, a citation footprint across trusted third-party sources, a complete and consistent business profile across Google, Apple and Bing, and topical clarity on your own website that matches the query intent.",
  },
  {
    q: "Can Search AI improve traditional local SEO too?",
    a: "Yes. Many of the signals that drive AI visibility, complete Google Business Profile, accurate categories, fresh multilingual reviews, schema markup, also drive Local Pack and Maps rankings. We measure both. Customers typically see lifts in both AI Overview citation share and Local Pack visibility in the first 60 days, with the AI side outpacing the SEO side after that as Google continues to expand the AI Overview surface.",
  },
  {
    q: "What types of Dubai businesses benefit most from Search AI?",
    a: "Any business where the customer journey starts with a search query that has commercial intent. Hospitality and dining are the biggest because international visitors plan from abroad and rely on AI to triage choices. Healthcare, aesthetic clinics, real estate, financial services, automotive and home services all see meaningful AI traffic share. Pure B2B with long sales cycles benefits less in the short term but should still establish a baseline.",
  },
  {
    q: "Does Search AI explain why an engine interprets my brand a certain way?",
    a: "Yes. For every query the dashboard captures the full AI answer, the cited sources, and the reasoning trace where available. You can see verbatim how Gemini described you, which sentence in which review it likely drew from, and which competitor it positioned ahead of you and why. That is the input to the prioritisation engine that decides which fix to run first.",
  },
  {
    q: "What actions can I take based on Search AI insights?",
    a: "Agents can push: Google Business Profile updates, multilingual review request campaigns, on-site service-page rewrites with the right schema, FAQ blocks that match high-intent Dubai queries, location-specific landing pages, and review responses in the right language. The human team handles press placements and dispute filings. The agents handle the recurring, structured work that AI engines re-read on every crawl.",
  },
  {
    q: "Can I track improvements over time?",
    a: "Yes. The dashboard reports weekly share of voice per engine, per location, per language, with trend lines back to your baseline week. You can pin specific high-intent queries to a watchlist, see citation lifts per source, and export anything to monthly stakeholder reports. The 90-day money-back guarantee is anchored to the metrics you and we agree on at the start of the engagement.",
  },
];

export function FAQSection() {
  const [open, setOpen] = useState<number | null>(null);
  return (
    <section
      className="bg-white py-16 lg:py-24"
      style={{ fontFamily: "'Roboto', sans-serif" }}
      aria-label="Frequently asked questions"
    >
      <div className="max-w-[1499px] mx-auto px-5 sm:px-6 lg:px-10">
        <h2
          className="text-[#0f0f0f] font-medium leading-[1.15] tracking-[-0.02em] mb-12 lg:mb-16"
          style={{ fontSize: "clamp(1.75rem, 3.4vw, 2.75rem)" }}
        >
          Frequently asked questions
        </h2>
        <div>
          {FAQ.map((item, i) => {
            const isOpen = open === i;
            return (
              <div key={i} className="border-b border-[#e5e5e5]">
                <button
                  type="button"
                  onClick={() => setOpen(isOpen ? null : i)}
                  className="w-full flex items-start justify-between gap-6 py-6 lg:py-7 text-left"
                  aria-expanded={isOpen}
                >
                  <span className="text-[#0f0f0f] text-[16px] sm:text-[18px] font-medium leading-[1.45] tracking-[-0.01em]">
                    {item.q}
                  </span>
                  <span
                    className="flex-shrink-0 w-7 h-7 rounded-full border border-[#0f0f0f] flex items-center justify-center text-[16px] leading-none"
                    aria-hidden="true"
                  >
                    {isOpen ? "–" : "+"}
                  </span>
                </button>
                {isOpen && (
                  <div className="pb-7 lg:pb-8 pr-12">
                    <p className="text-[#444] text-[15px] sm:text-[16px] leading-[1.7]">
                      {item.a}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
